// Package measureapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package measureapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostAlertBattery request with any body
	PostAlertBatteryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertBattery(ctx context.Context, body PostAlertBatteryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAlertConnection request with any body
	PostAlertConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertConnection(ctx context.Context, body PostAlertConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAlertDemand request with any body
	PostAlertDemandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertDemand(ctx context.Context, body PostAlertDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAlertSensor request with any body
	PostAlertSensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertSensor(ctx context.Context, body PostAlertSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAlertSystem request with any body
	PostAlertSystemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertSystem(ctx context.Context, body PostAlertSystemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAlertUps request with any body
	PostAlertUpsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAlertUps(ctx context.Context, body PostAlertUpsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDemand request with any body
	PostDemandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDemand(ctx context.Context, body PostDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEnergySensor request with any body
	PostEnergySensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEnergySensor(ctx context.Context, body PostEnergySensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEnvironmentalSensor request with any body
	PostEnvironmentalSensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEnvironmentalSensor(ctx context.Context, body PostEnvironmentalSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEquipmentState request with any body
	PostEquipmentStateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEquipmentState(ctx context.Context, body PostEquipmentStateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostInputContact request with any body
	PostInputContactWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostInputContact(ctx context.Context, body PostInputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOutputContact request with any body
	PostOutputContactWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOutputContact(ctx context.Context, body PostOutputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostAlertBatteryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertBatteryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertBattery(ctx context.Context, body PostAlertBatteryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertBatteryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertConnectionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertConnection(ctx context.Context, body PostAlertConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertConnectionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertDemandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertDemandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertDemand(ctx context.Context, body PostAlertDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertDemandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertSensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertSensorRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertSensor(ctx context.Context, body PostAlertSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertSensorRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertSystemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertSystemRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertSystem(ctx context.Context, body PostAlertSystemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertSystemRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertUpsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertUpsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAlertUps(ctx context.Context, body PostAlertUpsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAlertUpsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDemandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDemandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDemand(ctx context.Context, body PostDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDemandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEnergySensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEnergySensorRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEnergySensor(ctx context.Context, body PostEnergySensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEnergySensorRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEnvironmentalSensorWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEnvironmentalSensorRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEnvironmentalSensor(ctx context.Context, body PostEnvironmentalSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEnvironmentalSensorRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEquipmentStateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEquipmentStateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEquipmentState(ctx context.Context, body PostEquipmentStateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEquipmentStateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostInputContactWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInputContactRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostInputContact(ctx context.Context, body PostInputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInputContactRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOutputContactWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOutputContactRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOutputContact(ctx context.Context, body PostOutputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOutputContactRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostAlertBatteryRequest calls the generic PostAlertBattery builder with application/json body
func NewPostAlertBatteryRequest(server string, body PostAlertBatteryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertBatteryRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertBatteryRequestWithBody generates requests for PostAlertBattery with any type of body
func NewPostAlertBatteryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/battery")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAlertConnectionRequest calls the generic PostAlertConnection builder with application/json body
func NewPostAlertConnectionRequest(server string, body PostAlertConnectionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertConnectionRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertConnectionRequestWithBody generates requests for PostAlertConnection with any type of body
func NewPostAlertConnectionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/connection")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAlertDemandRequest calls the generic PostAlertDemand builder with application/json body
func NewPostAlertDemandRequest(server string, body PostAlertDemandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertDemandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertDemandRequestWithBody generates requests for PostAlertDemand with any type of body
func NewPostAlertDemandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/demand")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAlertSensorRequest calls the generic PostAlertSensor builder with application/json body
func NewPostAlertSensorRequest(server string, body PostAlertSensorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertSensorRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertSensorRequestWithBody generates requests for PostAlertSensor with any type of body
func NewPostAlertSensorRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/sensor")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAlertSystemRequest calls the generic PostAlertSystem builder with application/json body
func NewPostAlertSystemRequest(server string, body PostAlertSystemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertSystemRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertSystemRequestWithBody generates requests for PostAlertSystem with any type of body
func NewPostAlertSystemRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/system")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAlertUpsRequest calls the generic PostAlertUps builder with application/json body
func NewPostAlertUpsRequest(server string, body PostAlertUpsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAlertUpsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAlertUpsRequestWithBody generates requests for PostAlertUps with any type of body
func NewPostAlertUpsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alert/ups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostDemandRequest calls the generic PostDemand builder with application/json body
func NewPostDemandRequest(server string, body PostDemandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDemandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostDemandRequestWithBody generates requests for PostDemand with any type of body
func NewPostDemandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/demand")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEnergySensorRequest calls the generic PostEnergySensor builder with application/json body
func NewPostEnergySensorRequest(server string, body PostEnergySensorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEnergySensorRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEnergySensorRequestWithBody generates requests for PostEnergySensor with any type of body
func NewPostEnergySensorRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/energy-sensor")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEnvironmentalSensorRequest calls the generic PostEnvironmentalSensor builder with application/json body
func NewPostEnvironmentalSensorRequest(server string, body PostEnvironmentalSensorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEnvironmentalSensorRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEnvironmentalSensorRequestWithBody generates requests for PostEnvironmentalSensor with any type of body
func NewPostEnvironmentalSensorRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/environmental-sensor")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEquipmentStateRequest calls the generic PostEquipmentState builder with application/json body
func NewPostEquipmentStateRequest(server string, body PostEquipmentStateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEquipmentStateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEquipmentStateRequestWithBody generates requests for PostEquipmentState with any type of body
func NewPostEquipmentStateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/equipment-state")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostInputContactRequest calls the generic PostInputContact builder with application/json body
func NewPostInputContactRequest(server string, body PostInputContactJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostInputContactRequestWithBody(server, "application/json", bodyReader)
}

// NewPostInputContactRequestWithBody generates requests for PostInputContact with any type of body
func NewPostInputContactRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/input-contact")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOutputContactRequest calls the generic PostOutputContact builder with application/json body
func NewPostOutputContactRequest(server string, body PostOutputContactJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOutputContactRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOutputContactRequestWithBody generates requests for PostOutputContact with any type of body
func NewPostOutputContactRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/output-contact")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostAlertBattery request with any body
	PostAlertBatteryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertBatteryResponse, error)

	PostAlertBatteryWithResponse(ctx context.Context, body PostAlertBatteryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertBatteryResponse, error)

	// PostAlertConnection request with any body
	PostAlertConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertConnectionResponse, error)

	PostAlertConnectionWithResponse(ctx context.Context, body PostAlertConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertConnectionResponse, error)

	// PostAlertDemand request with any body
	PostAlertDemandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertDemandResponse, error)

	PostAlertDemandWithResponse(ctx context.Context, body PostAlertDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertDemandResponse, error)

	// PostAlertSensor request with any body
	PostAlertSensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertSensorResponse, error)

	PostAlertSensorWithResponse(ctx context.Context, body PostAlertSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertSensorResponse, error)

	// PostAlertSystem request with any body
	PostAlertSystemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertSystemResponse, error)

	PostAlertSystemWithResponse(ctx context.Context, body PostAlertSystemJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertSystemResponse, error)

	// PostAlertUps request with any body
	PostAlertUpsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertUpsResponse, error)

	PostAlertUpsWithResponse(ctx context.Context, body PostAlertUpsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertUpsResponse, error)

	// PostDemand request with any body
	PostDemandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDemandResponse, error)

	PostDemandWithResponse(ctx context.Context, body PostDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDemandResponse, error)

	// PostEnergySensor request with any body
	PostEnergySensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEnergySensorResponse, error)

	PostEnergySensorWithResponse(ctx context.Context, body PostEnergySensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEnergySensorResponse, error)

	// PostEnvironmentalSensor request with any body
	PostEnvironmentalSensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEnvironmentalSensorResponse, error)

	PostEnvironmentalSensorWithResponse(ctx context.Context, body PostEnvironmentalSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEnvironmentalSensorResponse, error)

	// PostEquipmentState request with any body
	PostEquipmentStateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEquipmentStateResponse, error)

	PostEquipmentStateWithResponse(ctx context.Context, body PostEquipmentStateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEquipmentStateResponse, error)

	// PostInputContact request with any body
	PostInputContactWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInputContactResponse, error)

	PostInputContactWithResponse(ctx context.Context, body PostInputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInputContactResponse, error)

	// PostOutputContact request with any body
	PostOutputContactWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOutputContactResponse, error)

	PostOutputContactWithResponse(ctx context.Context, body PostOutputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOutputContactResponse, error)
}

type PostAlertBatteryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertBatteryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertBatteryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAlertConnectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertConnectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertConnectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAlertDemandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertDemandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertDemandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAlertSensorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertSensorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertSensorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAlertSystemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertSystemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertSystemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAlertUpsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostAlertUpsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAlertUpsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDemandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostDemandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDemandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEnergySensorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostEnergySensorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEnergySensorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEnvironmentalSensorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostEnvironmentalSensorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEnvironmentalSensorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEquipmentStateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostEquipmentStateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEquipmentStateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostInputContactResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostInputContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostInputContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOutputContactResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostResponse
}

// Status returns HTTPResponse.Status
func (r PostOutputContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOutputContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostAlertBatteryWithBodyWithResponse request with arbitrary body returning *PostAlertBatteryResponse
func (c *ClientWithResponses) PostAlertBatteryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertBatteryResponse, error) {
	rsp, err := c.PostAlertBatteryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertBatteryResponse(rsp)
}

func (c *ClientWithResponses) PostAlertBatteryWithResponse(ctx context.Context, body PostAlertBatteryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertBatteryResponse, error) {
	rsp, err := c.PostAlertBattery(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertBatteryResponse(rsp)
}

// PostAlertConnectionWithBodyWithResponse request with arbitrary body returning *PostAlertConnectionResponse
func (c *ClientWithResponses) PostAlertConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertConnectionResponse, error) {
	rsp, err := c.PostAlertConnectionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertConnectionResponse(rsp)
}

func (c *ClientWithResponses) PostAlertConnectionWithResponse(ctx context.Context, body PostAlertConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertConnectionResponse, error) {
	rsp, err := c.PostAlertConnection(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertConnectionResponse(rsp)
}

// PostAlertDemandWithBodyWithResponse request with arbitrary body returning *PostAlertDemandResponse
func (c *ClientWithResponses) PostAlertDemandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertDemandResponse, error) {
	rsp, err := c.PostAlertDemandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertDemandResponse(rsp)
}

func (c *ClientWithResponses) PostAlertDemandWithResponse(ctx context.Context, body PostAlertDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertDemandResponse, error) {
	rsp, err := c.PostAlertDemand(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertDemandResponse(rsp)
}

// PostAlertSensorWithBodyWithResponse request with arbitrary body returning *PostAlertSensorResponse
func (c *ClientWithResponses) PostAlertSensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertSensorResponse, error) {
	rsp, err := c.PostAlertSensorWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertSensorResponse(rsp)
}

func (c *ClientWithResponses) PostAlertSensorWithResponse(ctx context.Context, body PostAlertSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertSensorResponse, error) {
	rsp, err := c.PostAlertSensor(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertSensorResponse(rsp)
}

// PostAlertSystemWithBodyWithResponse request with arbitrary body returning *PostAlertSystemResponse
func (c *ClientWithResponses) PostAlertSystemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertSystemResponse, error) {
	rsp, err := c.PostAlertSystemWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertSystemResponse(rsp)
}

func (c *ClientWithResponses) PostAlertSystemWithResponse(ctx context.Context, body PostAlertSystemJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertSystemResponse, error) {
	rsp, err := c.PostAlertSystem(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertSystemResponse(rsp)
}

// PostAlertUpsWithBodyWithResponse request with arbitrary body returning *PostAlertUpsResponse
func (c *ClientWithResponses) PostAlertUpsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAlertUpsResponse, error) {
	rsp, err := c.PostAlertUpsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertUpsResponse(rsp)
}

func (c *ClientWithResponses) PostAlertUpsWithResponse(ctx context.Context, body PostAlertUpsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAlertUpsResponse, error) {
	rsp, err := c.PostAlertUps(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAlertUpsResponse(rsp)
}

// PostDemandWithBodyWithResponse request with arbitrary body returning *PostDemandResponse
func (c *ClientWithResponses) PostDemandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDemandResponse, error) {
	rsp, err := c.PostDemandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDemandResponse(rsp)
}

func (c *ClientWithResponses) PostDemandWithResponse(ctx context.Context, body PostDemandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDemandResponse, error) {
	rsp, err := c.PostDemand(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDemandResponse(rsp)
}

// PostEnergySensorWithBodyWithResponse request with arbitrary body returning *PostEnergySensorResponse
func (c *ClientWithResponses) PostEnergySensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEnergySensorResponse, error) {
	rsp, err := c.PostEnergySensorWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEnergySensorResponse(rsp)
}

func (c *ClientWithResponses) PostEnergySensorWithResponse(ctx context.Context, body PostEnergySensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEnergySensorResponse, error) {
	rsp, err := c.PostEnergySensor(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEnergySensorResponse(rsp)
}

// PostEnvironmentalSensorWithBodyWithResponse request with arbitrary body returning *PostEnvironmentalSensorResponse
func (c *ClientWithResponses) PostEnvironmentalSensorWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEnvironmentalSensorResponse, error) {
	rsp, err := c.PostEnvironmentalSensorWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEnvironmentalSensorResponse(rsp)
}

func (c *ClientWithResponses) PostEnvironmentalSensorWithResponse(ctx context.Context, body PostEnvironmentalSensorJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEnvironmentalSensorResponse, error) {
	rsp, err := c.PostEnvironmentalSensor(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEnvironmentalSensorResponse(rsp)
}

// PostEquipmentStateWithBodyWithResponse request with arbitrary body returning *PostEquipmentStateResponse
func (c *ClientWithResponses) PostEquipmentStateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEquipmentStateResponse, error) {
	rsp, err := c.PostEquipmentStateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEquipmentStateResponse(rsp)
}

func (c *ClientWithResponses) PostEquipmentStateWithResponse(ctx context.Context, body PostEquipmentStateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEquipmentStateResponse, error) {
	rsp, err := c.PostEquipmentState(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEquipmentStateResponse(rsp)
}

// PostInputContactWithBodyWithResponse request with arbitrary body returning *PostInputContactResponse
func (c *ClientWithResponses) PostInputContactWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInputContactResponse, error) {
	rsp, err := c.PostInputContactWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInputContactResponse(rsp)
}

func (c *ClientWithResponses) PostInputContactWithResponse(ctx context.Context, body PostInputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInputContactResponse, error) {
	rsp, err := c.PostInputContact(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInputContactResponse(rsp)
}

// PostOutputContactWithBodyWithResponse request with arbitrary body returning *PostOutputContactResponse
func (c *ClientWithResponses) PostOutputContactWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOutputContactResponse, error) {
	rsp, err := c.PostOutputContactWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOutputContactResponse(rsp)
}

func (c *ClientWithResponses) PostOutputContactWithResponse(ctx context.Context, body PostOutputContactJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOutputContactResponse, error) {
	rsp, err := c.PostOutputContact(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOutputContactResponse(rsp)
}

// ParsePostAlertBatteryResponse parses an HTTP response from a PostAlertBatteryWithResponse call
func ParsePostAlertBatteryResponse(rsp *http.Response) (*PostAlertBatteryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertBatteryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAlertConnectionResponse parses an HTTP response from a PostAlertConnectionWithResponse call
func ParsePostAlertConnectionResponse(rsp *http.Response) (*PostAlertConnectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertConnectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAlertDemandResponse parses an HTTP response from a PostAlertDemandWithResponse call
func ParsePostAlertDemandResponse(rsp *http.Response) (*PostAlertDemandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertDemandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAlertSensorResponse parses an HTTP response from a PostAlertSensorWithResponse call
func ParsePostAlertSensorResponse(rsp *http.Response) (*PostAlertSensorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertSensorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAlertSystemResponse parses an HTTP response from a PostAlertSystemWithResponse call
func ParsePostAlertSystemResponse(rsp *http.Response) (*PostAlertSystemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertSystemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAlertUpsResponse parses an HTTP response from a PostAlertUpsWithResponse call
func ParsePostAlertUpsResponse(rsp *http.Response) (*PostAlertUpsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAlertUpsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostDemandResponse parses an HTTP response from a PostDemandWithResponse call
func ParsePostDemandResponse(rsp *http.Response) (*PostDemandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDemandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEnergySensorResponse parses an HTTP response from a PostEnergySensorWithResponse call
func ParsePostEnergySensorResponse(rsp *http.Response) (*PostEnergySensorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEnergySensorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEnvironmentalSensorResponse parses an HTTP response from a PostEnvironmentalSensorWithResponse call
func ParsePostEnvironmentalSensorResponse(rsp *http.Response) (*PostEnvironmentalSensorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEnvironmentalSensorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEquipmentStateResponse parses an HTTP response from a PostEquipmentStateWithResponse call
func ParsePostEquipmentStateResponse(rsp *http.Response) (*PostEquipmentStateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEquipmentStateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostInputContactResponse parses an HTTP response from a PostInputContactWithResponse call
func ParsePostInputContactResponse(rsp *http.Response) (*PostInputContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostInputContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostOutputContactResponse parses an HTTP response from a PostOutputContactWithResponse call
func ParsePostOutputContactResponse(rsp *http.Response) (*PostOutputContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOutputContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
