// Package measureapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package measureapi

import (
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 電池残量アラートの登録
	// (POST /alert/battery)
	PostAlertBattery(ctx echo.Context) error
	// 通信アラート状況の登録
	// (POST /alert/connection)
	PostAlertConnection(ctx echo.Context) error
	// デマンドアラートの登録
	// (POST /alert/demand)
	PostAlertDemand(ctx echo.Context) error
	// センサー監視アラートの登録
	// (POST /alert/sensor)
	PostAlertSensor(ctx echo.Context) error
	// 親機システムアラートの登録
	// (POST /alert/system)
	PostAlertSystem(ctx echo.Context) error
	// 親機電源アラートの登録
	// (POST /alert/ups)
	PostAlertUps(ctx echo.Context) error
	// デマンドデータの登録
	// (POST /demand)
	PostDemand(ctx echo.Context) error
	// エネルギーセンサーデータの登録
	// (POST /energy-sensor)
	PostEnergySensor(ctx echo.Context) error
	// 環境センサーデータの登録
	// (POST /environmental-sensor)
	PostEnvironmentalSensor(ctx echo.Context) error
	// 機器別ステートの登録
	// (POST /equipment-state)
	PostEquipmentState(ctx echo.Context) error
	// 入力接点データの登録
	// (POST /input-contact)
	PostInputContact(ctx echo.Context) error
	// 出力接点データの登録
	// (POST /output-contact)
	PostOutputContact(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAlertBattery converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertBattery(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertBattery(ctx)
	return err
}

// PostAlertConnection converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertConnection(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertConnection(ctx)
	return err
}

// PostAlertDemand converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertDemand(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertDemand(ctx)
	return err
}

// PostAlertSensor converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertSensor(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertSensor(ctx)
	return err
}

// PostAlertSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertSystem(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertSystem(ctx)
	return err
}

// PostAlertUps converts echo context to params.
func (w *ServerInterfaceWrapper) PostAlertUps(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostAlertUps(ctx)
	return err
}

// PostDemand converts echo context to params.
func (w *ServerInterfaceWrapper) PostDemand(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostDemand(ctx)
	return err
}

// PostEnergySensor converts echo context to params.
func (w *ServerInterfaceWrapper) PostEnergySensor(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostEnergySensor(ctx)
	return err
}

// PostEnvironmentalSensor converts echo context to params.
func (w *ServerInterfaceWrapper) PostEnvironmentalSensor(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostEnvironmentalSensor(ctx)
	return err
}

// PostEquipmentState converts echo context to params.
func (w *ServerInterfaceWrapper) PostEquipmentState(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostEquipmentState(ctx)
	return err
}

// PostInputContact converts echo context to params.
func (w *ServerInterfaceWrapper) PostInputContact(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostInputContact(ctx)
	return err
}

// PostOutputContact converts echo context to params.
func (w *ServerInterfaceWrapper) PostOutputContact(ctx echo.Context) error {
	var err error

	ctx.Set(ApiAuthorizerNameScopes, []string{""})

	ctx.Set(ApiKeyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostOutputContact(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/alert/battery", wrapper.PostAlertBattery)
	router.POST(baseURL+"/alert/connection", wrapper.PostAlertConnection)
	router.POST(baseURL+"/alert/demand", wrapper.PostAlertDemand)
	router.POST(baseURL+"/alert/sensor", wrapper.PostAlertSensor)
	router.POST(baseURL+"/alert/system", wrapper.PostAlertSystem)
	router.POST(baseURL+"/alert/ups", wrapper.PostAlertUps)
	router.POST(baseURL+"/demand", wrapper.PostDemand)
	router.POST(baseURL+"/energy-sensor", wrapper.PostEnergySensor)
	router.POST(baseURL+"/environmental-sensor", wrapper.PostEnvironmentalSensor)
	router.POST(baseURL+"/equipment-state", wrapper.PostEquipmentState)
	router.POST(baseURL+"/input-contact", wrapper.PostInputContact)
	router.POST(baseURL+"/output-contact", wrapper.PostOutputContact)

}
