// Package measureapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package measureapi

const (
	ApiAuthorizerNameScopes = "apiAuthorizerName.Scopes"
	ApiKeyScopes            = "apiKey.Scopes"
)

// Defines values for AlertSensorArgsKind.
const (
	AlertSensorArgsKindEnergySensor        AlertSensorArgsKind = "EnergySensor"
	AlertSensorArgsKindEnergySensorGroup   AlertSensorArgsKind = "EnergySensorGroup"
	AlertSensorArgsKindEnvironmentalSensor AlertSensorArgsKind = "EnvironmentalSensor"
	AlertSensorArgsKindInputContact        AlertSensorArgsKind = "InputContact"
	AlertSensorArgsKindOutputContact       AlertSensorArgsKind = "OutputContact"
)

// Defines values for ControlState.
const (
	AutoControl       ControlState = "AutoControl"
	Defrost           ControlState = "Defrost"
	DemandControl     ControlState = "DemandControl"
	Release           ControlState = "Release"
	RemoteControl     ControlState = "RemoteControl"
	RemoteDefrostStop ControlState = "RemoteDefrostStop"
	Unknown           ControlState = "Unknown"
)

// Defines values for DemandState.
const (
	Excess  DemandState = "Excess"
	Limit   DemandState = "Limit"
	Normal  DemandState = "Normal"
	Recover DemandState = "Recover"
	Warn    DemandState = "Warn"
)

// ActiveElectricEnergy **有効電力量（Wh）**
type ActiveElectricEnergy = float32

// ActiveElectricPower **有効電力（W）**
type ActiveElectricPower = float32

// AdjustedElectricity **調整電力(kw)**
type AdjustedElectricity = float32

// AlertBatteryArgs 電池残量アラート登録の引数
type AlertBatteryArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Id **デマンドパルス識別**
	Id string `json:"id"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// AlertConnectionArgs 通信アラート状況登録の引数
type AlertConnectionArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// ChildDeviceIds 接続できない**子機識別**（複数）
	ChildDeviceIds []string `json:"childDeviceIds"`

	// DemandPulseId 接続できない**デマンドパルス識別**（単数）
	DemandPulseId *string `json:"demandPulseId"`

	// EnergySensorIds 接続できない**エネルギーセンサー識別**（複数）
	EnergySensorIds []string `json:"energySensorIds"`

	// EnvironmentalSensorIds 接続できない**環境センサー識別**（複数）
	EnvironmentalSensorIds []string `json:"environmentalSensorIds"`

	// InputContactIds 接続できない**入力接点識別**（複数）
	InputContactIds []string `json:"inputContactIds"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// OutputContactIds 接続できない**出力接点識別**（複数）
	OutputContactIds []string `json:"outputContactIds"`

	// ParentDeviceId アラート送信元の**親機識別**
	ParentDeviceId string `json:"parentDeviceId"`
}

// AlertDemandArgs デマンドアラート登録の引数
type AlertDemandArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// DemandState **アラート状況**
	// `Normal`: 正常
	// `Warn`: 警戒
	// `Limit`: 限界
	// `Excess`: 超過
	// `Recover`: 復帰
	DemandState DemandState `json:"demandState"`

	// Id **デマンドパルス識別**
	Id string `json:"id"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// Message **現在電力(kw)**／**予測電力(kw)**／**目標電力(kw)**／**限界電力(kw)**の現在値を記載したメッセージ
	Message string `json:"message"`
}

// AlertSensorArgs センサー監視アラート登録の引数
type AlertSensorArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Id アラートを発報した項目の識別
	Id string `json:"id"`

	// Kind アラート発報したセンサーの種類
	// `EnergySensor`: エネルギーセンサー
	// `EnvironmentalSensor`: 環境センサー
	// `InputContact`: 入力接点
	// `OutputContact`: 出力接点
	Kind AlertSensorArgsKind `json:"kind"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// Message **アラート状況**
	Message string `json:"message"`

	// OccurredAt Unix time（epoch time）を示す数値（Second）
	// 一連のアラートの最初の発生時刻
	OccurredAt *OccurredAt `json:"occurredAt,omitempty"`

	// SensorMonitoringConditionId **センサー監視条件識別**
	SensorMonitoringConditionId string `json:"sensorMonitoringConditionId"`
}

// AlertSensorArgsKind アラート発報したセンサーの種類
// `EnergySensor`: エネルギーセンサー
// `EnvironmentalSensor`: 環境センサー
// `InputContact`: 入力接点
// `OutputContact`: 出力接点
type AlertSensorArgsKind string

// AlertSystemArgs 親機システムアラート登録の引数
type AlertSystemArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// ErrorCode エラーコード
	ErrorCode string `json:"errorCode"`

	// Id **親機識別**
	Id string `json:"id"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// Message アラートメッセージ
	Message string `json:"message"`
}

// AlertUpsArgs 親機電源アラート登録の引数
type AlertUpsArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Id **親機識別**
	Id string `json:"id"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// Message **アラート状況**
	Message string `json:"message"`
}

// BaseId **拠点識別**
type BaseId = string

// ControlOrder **制御命令**　（制御: true / 解除: false）
type ControlOrder = bool

// ControlState **制御状況**
// `DemandControl`: デマンド制御
// `AutoControl`: 自動制御
// `RemoteControl`: 遠隔制御
// `Release`: 解除
// `Defrost`: デフロスト
// `RemoteDefrostStop`: 遠隔デフロスト停止
// `Unknown`: 不明
type ControlState string

// CurrentElectricity **現在電力(kw)**
type CurrentElectricity = float32

// DemandArgs デマンドデータ登録の引数
type DemandArgs struct {
	// AdjustedElectricity **調整電力(kw)**
	AdjustedElectricity AdjustedElectricity `json:"adjustedElectricity"`

	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// CurrentElectricity **現在電力(kw)**
	CurrentElectricity CurrentElectricity `json:"currentElectricity"`

	// DemandState **アラート状況**
	// `Normal`: 正常
	// `Warn`: 警戒
	// `Limit`: 限界
	// `Excess`: 超過
	// `Recover`: 復帰
	DemandState DemandState `json:"demandState"`

	// Id **デマンドパルス識別**
	Id string `json:"id"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`

	// PredictedElectricity **予測電力(kw)**
	PredictedElectricity PredictedElectricity `json:"predictedElectricity"`

	// RemainingSeconds **残り時間（秒）**
	RemainingSeconds RemainingSeconds `json:"remainingSeconds"`
}

// DemandState **アラート状況**
// `Normal`: 正常
// `Warn`: 警戒
// `Limit`: 限界
// `Excess`: 超過
// `Recover`: 復帰
type DemandState string

// DiscomfortIndex **不快指数**
type DiscomfortIndex = float32

// ElectricCurrent1 **電流１**
type ElectricCurrent1 = float32

// ElectricCurrent2 **電流２**
type ElectricCurrent2 = float32

// ElectricCurrent3 **電流３**
type ElectricCurrent3 = float32

// ElectricEnergy 電力量（Wh）
type ElectricEnergy = float32

// ElectricPower 電力(w)
type ElectricPower = float32

// EnergySensor **エネルギーセンサーデータ**
type EnergySensor struct {
	// ActiveElectricEnergy **有効電力量（Wh）**
	ActiveElectricEnergy ActiveElectricEnergy `json:"activeElectricEnergy"`

	// ActiveElectricPower **有効電力（W）**
	ActiveElectricPower ActiveElectricPower `json:"activeElectricPower"`

	// ElectricCurrent1 **電流１**
	ElectricCurrent1 ElectricCurrent1 `json:"electricCurrent1"`

	// ElectricCurrent2 **電流２**
	ElectricCurrent2 ElectricCurrent2 `json:"electricCurrent2"`

	// ElectricCurrent3 **電流３**
	ElectricCurrent3 ElectricCurrent3 `json:"electricCurrent3"`

	// Frequency **周波数**
	Frequency Frequency `json:"frequency"`

	// Id **エネルギーセンサー識別**
	Id string `json:"id"`

	// PowerFactor **力率**
	PowerFactor PowerFactor `json:"powerFactor"`

	// Voltage1 **電圧１**
	Voltage1 Voltage1 `json:"voltage1"`

	// Voltage2 **電圧２**
	Voltage2 Voltage2 `json:"voltage2"`

	// Voltage3 **電圧３**
	Voltage3 Voltage3 `json:"voltage3"`
}

// EnergySensorArgs エネルギーセンサーデータ登録の引数
type EnergySensorArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Data エネルギーセンサーデータの配列
	Data EnergySensors `json:"data"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// EnergySensors エネルギーセンサーデータの配列
type EnergySensors = []EnergySensor

// EnvironmentalSensor 環境センサーデータ
type EnvironmentalSensor struct {
	// DiscomfortIndex **不快指数**
	DiscomfortIndex DiscomfortIndex `json:"discomfortIndex"`

	// Humidity **湿度**
	Humidity Humidity `json:"humidity"`

	// Id **環境センサー識別**
	Id string `json:"id"`

	// Temperature **温度**
	Temperature Temperature `json:"temperature"`
}

// EnvironmentalSensorArgs 環境センサーデータ登録の引数
type EnvironmentalSensorArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Data 環境センサーデータの配列
	Data EnvironmentalSensors `json:"data"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// EnvironmentalSensors 環境センサーデータの配列
type EnvironmentalSensors = []EnvironmentalSensor

// EquipmentState 機器別ステートデータ
type EquipmentState struct {
	// ControlOrder **制御命令**　（制御: true / 解除: false）
	ControlOrder ControlOrder `json:"controlOrder"`

	// ControlState **制御状況**
	// `DemandControl`: デマンド制御
	// `AutoControl`: 自動制御
	// `RemoteControl`: 遠隔制御
	// `Release`: 解除
	// `Defrost`: デフロスト
	// `RemoteDefrostStop`: 遠隔デフロスト停止
	// `Unknown`: 不明
	ControlState ControlState `json:"controlState"`

	// ElectricEnergy 電力量（Wh）
	ElectricEnergy ElectricEnergy `json:"electricEnergy"`

	// ElectricPower 電力(w)
	ElectricPower ElectricPower `json:"electricPower"`

	// Id **機器識別**
	Id string `json:"id"`

	// Operating 機器が稼働しているかどうか
	// 電力＞稼働判断電力　の結果
	Operating Operating `json:"operating"`

	// OperatingRate **稼働率**（少数表記）
	OperatingRate OperatingRate `json:"operatingRate"`
}

// EquipmentStateArgs 機器別ステート登録の引数
type EquipmentStateArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Data 機器データの配列
	Data EquipmentStates `json:"data"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// EquipmentStates 機器データの配列
type EquipmentStates = []EquipmentState

// Frequency **周波数**
type Frequency = float32

// Humidity **湿度**
type Humidity = float32

// InputContact 入力接点データ
type InputContact struct {
	// Id **入力接点識別**
	Id string `json:"id"`

	// Status **入力データ**　状態（ON: true / OFF: false）
	Status bool `json:"status"`
}

// InputContactArgs 入力接点データ登録の引数
type InputContactArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Data 入力接点データの配列
	Data InputContacts `json:"data"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// InputContacts 入力接点データの配列
type InputContacts = []InputContact

// MeasuredAt Unix time（epoch time）を示す数値（Second）
type MeasuredAt = int

// OccurredAt Unix time（epoch time）を示す数値（Second）
// 一連のアラートの最初の発生時刻
type OccurredAt = int

// Operating 機器が稼働しているかどうか
// 電力＞稼働判断電力　の結果
type Operating = bool

// OperatingRate **稼働率**（少数表記）
type OperatingRate = float32

// OutputContact 出力接点データ
type OutputContact struct {
	// Id **出力接点識別**
	Id string `json:"id"`

	// Status **出力データ**　状態（ON: true / OFF: false）
	Status bool `json:"status"`
}

// OutputContactArgs 出力接点データ登録の引数
type OutputContactArgs struct {
	// BaseId **拠点識別**
	BaseId BaseId `json:"baseId"`

	// Data 出力接点データの配列
	Data OutputContacts `json:"data"`

	// MeasuredAt Unix time（epoch time）を示す数値（Second）
	MeasuredAt MeasuredAt `json:"measuredAt"`
}

// OutputContacts 出力接点データの配列
type OutputContacts = []OutputContact

// PostResponse 送信成功時のレスポンス
type PostResponse struct {
	// Message レスポンスメッセージ
	Message *string `json:"message,omitempty"`

	// TraceId トレース用ID
	TraceId *string `json:"traceId,omitempty"`
}

// PowerFactor **力率**
type PowerFactor = float32

// PredictedElectricity **予測電力(kw)**
type PredictedElectricity = float32

// RemainingSeconds **残り時間（秒）**
type RemainingSeconds = int

// Temperature **温度**
type Temperature = float32

// Voltage1 **電圧１**
type Voltage1 = float32

// Voltage2 **電圧２**
type Voltage2 = float32

// Voltage3 **電圧３**
type Voltage3 = float32

// PostAlertBatteryJSONRequestBody defines body for PostAlertBattery for application/json ContentType.
type PostAlertBatteryJSONRequestBody = AlertBatteryArgs

// PostAlertConnectionJSONRequestBody defines body for PostAlertConnection for application/json ContentType.
type PostAlertConnectionJSONRequestBody = AlertConnectionArgs

// PostAlertDemandJSONRequestBody defines body for PostAlertDemand for application/json ContentType.
type PostAlertDemandJSONRequestBody = AlertDemandArgs

// PostAlertSensorJSONRequestBody defines body for PostAlertSensor for application/json ContentType.
type PostAlertSensorJSONRequestBody = AlertSensorArgs

// PostAlertSystemJSONRequestBody defines body for PostAlertSystem for application/json ContentType.
type PostAlertSystemJSONRequestBody = AlertSystemArgs

// PostAlertUpsJSONRequestBody defines body for PostAlertUps for application/json ContentType.
type PostAlertUpsJSONRequestBody = AlertUpsArgs

// PostDemandJSONRequestBody defines body for PostDemand for application/json ContentType.
type PostDemandJSONRequestBody = DemandArgs

// PostEnergySensorJSONRequestBody defines body for PostEnergySensor for application/json ContentType.
type PostEnergySensorJSONRequestBody = EnergySensorArgs

// PostEnvironmentalSensorJSONRequestBody defines body for PostEnvironmentalSensor for application/json ContentType.
type PostEnvironmentalSensorJSONRequestBody = EnvironmentalSensorArgs

// PostEquipmentStateJSONRequestBody defines body for PostEquipmentState for application/json ContentType.
type PostEquipmentStateJSONRequestBody = EquipmentStateArgs

// PostInputContactJSONRequestBody defines body for PostInputContact for application/json ContentType.
type PostInputContactJSONRequestBody = InputContactArgs

// PostOutputContactJSONRequestBody defines body for PostOutputContact for application/json ContentType.
type PostOutputContactJSONRequestBody = OutputContactArgs
