@startuml boot
!pragma teoz true
title センサー情報通知シーケンス

participant linux
participant schedule
participant cloud
participant child
participant aram
participant demand
database    内部SQL
database    クラウド
database    アラートFIFO

== (8)-4 通信接続監視（正常） ==
== (8)-4 通信接続監視（異常） ==

@enduml
