// Package syncapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package syncapi

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// デマンド制御命令の取得
	// (GET /api/bases/{id}/demand-control-order)
	BasesControllerGetDemandControlOrder(ctx echo.Context, id string) error
	// 機器の緊急制御命令の取得
	// (GET /api/bases/{id}/manual-control-orders)
	BasesControllerGetManualControlOrders(ctx echo.Context, id string) error
	// 出力接点の緊急デフロスト命令の取得
	// (GET /api/bases/{id}/manual-defrost-orders)
	BasesControllerGetManualDefrostOrders(ctx echo.Context, id string) error
	// 機器の緊急制御解除命令完了を通知
	// (POST /api/equipments/{id}/released)
	EquipmentsControllerReleaseManualControlOrder(ctx echo.Context, id string) error
	// 親機に紐づくデータを取得
	// (GET /api/parent-devices/{id})
	ParentDevicesControllerGetParentDevice(ctx echo.Context, id string) error
	// 親機の再起動命令を取得
	// (GET /api/parent-devices/{id}/parent-device-restart-order)
	ParentDevicesControllerGetParentDeviceRestartOrder(ctx echo.Context, id string) error
	// 親機の再起動完了を通知
	// (POST /api/parent-devices/{id}/restarted)
	ParentDevicesControllerCompleteParentDeviceRestart(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// BasesControllerGetDemandControlOrder converts echo context to params.
func (w *ServerInterfaceWrapper) BasesControllerGetDemandControlOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.BasesControllerGetDemandControlOrder(ctx, id)
	return err
}

// BasesControllerGetManualControlOrders converts echo context to params.
func (w *ServerInterfaceWrapper) BasesControllerGetManualControlOrders(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.BasesControllerGetManualControlOrders(ctx, id)
	return err
}

// BasesControllerGetManualDefrostOrders converts echo context to params.
func (w *ServerInterfaceWrapper) BasesControllerGetManualDefrostOrders(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.BasesControllerGetManualDefrostOrders(ctx, id)
	return err
}

// EquipmentsControllerReleaseManualControlOrder converts echo context to params.
func (w *ServerInterfaceWrapper) EquipmentsControllerReleaseManualControlOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.EquipmentsControllerReleaseManualControlOrder(ctx, id)
	return err
}

// ParentDevicesControllerGetParentDevice converts echo context to params.
func (w *ServerInterfaceWrapper) ParentDevicesControllerGetParentDevice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ParentDevicesControllerGetParentDevice(ctx, id)
	return err
}

// ParentDevicesControllerGetParentDeviceRestartOrder converts echo context to params.
func (w *ServerInterfaceWrapper) ParentDevicesControllerGetParentDeviceRestartOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ParentDevicesControllerGetParentDeviceRestartOrder(ctx, id)
	return err
}

// ParentDevicesControllerCompleteParentDeviceRestart converts echo context to params.
func (w *ServerInterfaceWrapper) ParentDevicesControllerCompleteParentDeviceRestart(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(X_api_keyScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ParentDevicesControllerCompleteParentDeviceRestart(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/bases/:id/demand-control-order", wrapper.BasesControllerGetDemandControlOrder)
	router.GET(baseURL+"/api/bases/:id/manual-control-orders", wrapper.BasesControllerGetManualControlOrders)
	router.GET(baseURL+"/api/bases/:id/manual-defrost-orders", wrapper.BasesControllerGetManualDefrostOrders)
	router.POST(baseURL+"/api/equipments/:id/released", wrapper.EquipmentsControllerReleaseManualControlOrder)
	router.GET(baseURL+"/api/parent-devices/:id", wrapper.ParentDevicesControllerGetParentDevice)
	router.GET(baseURL+"/api/parent-devices/:id/parent-device-restart-order", wrapper.ParentDevicesControllerGetParentDeviceRestartOrder)
	router.POST(baseURL+"/api/parent-devices/:id/restarted", wrapper.ParentDevicesControllerCompleteParentDeviceRestart)

}
