// Package syncapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package syncapi

const (
	X_api_keyScopes = "x_api_key.Scopes"
)

// Defines values for EnvironmentalSensorForLocalCategory.
const (
	EnvironmentalSensorForLocalCategoryHumidity    EnvironmentalSensorForLocalCategory = "Humidity"
	EnvironmentalSensorForLocalCategoryTemperature EnvironmentalSensorForLocalCategory = "Temperature"
)

// Defines values for EquipmentForLocalJudgmentCriteria.
const (
	Average EquipmentForLocalJudgmentCriteria = "Average"
	Max     EquipmentForLocalJudgmentCriteria = "Max"
	Min     EquipmentForLocalJudgmentCriteria = "Min"
)

// Defines values for EquipmentForLocalMode.
const (
	Auto    EquipmentForLocalMode = "Auto"
	Cooling EquipmentForLocalMode = "Cooling"
	Heating EquipmentForLocalMode = "Heating"
)

// Defines values for InputContactForLocalCategory.
const (
	Breaker InputContactForLocalCategory = "Breaker"
	Defrost InputContactForLocalCategory = "Defrost"
	Etc     InputContactForLocalCategory = "Etc"
)

// Defines values for OutputContactForLocalCategory.
const (
	Control        OutputContactForLocalCategory = "Control"
	DefrostControl OutputContactForLocalCategory = "DefrostControl"
)

// Defines values for OutputContactForLocalControlMethod.
const (
	Capacity OutputContactForLocalControlMethod = "Capacity"
	Stop     OutputContactForLocalControlMethod = "Stop"
)

// Defines values for SensorMonitoringConditionForLocalAnomalyType.
const (
	Less SensorMonitoringConditionForLocalAnomalyType = "Less"
	More SensorMonitoringConditionForLocalAnomalyType = "More"
	OFF  SensorMonitoringConditionForLocalAnomalyType = "OFF"
	ON   SensorMonitoringConditionForLocalAnomalyType = "ON"
)

// Defines values for SensorMonitoringConditionForLocalCategory.
const (
	SensorMonitoringConditionForLocalCategoryBatteryLevel     SensorMonitoringConditionForLocalCategory = "BatteryLevel"
	SensorMonitoringConditionForLocalCategoryBreaker          SensorMonitoringConditionForLocalCategory = "Breaker"
	SensorMonitoringConditionForLocalCategoryControl          SensorMonitoringConditionForLocalCategory = "Control"
	SensorMonitoringConditionForLocalCategoryDiscomfortIndex  SensorMonitoringConditionForLocalCategory = "DiscomfortIndex"
	SensorMonitoringConditionForLocalCategoryElectricCurrent1 SensorMonitoringConditionForLocalCategory = "ElectricCurrent1"
	SensorMonitoringConditionForLocalCategoryElectricCurrent2 SensorMonitoringConditionForLocalCategory = "ElectricCurrent2"
	SensorMonitoringConditionForLocalCategoryElectricCurrent3 SensorMonitoringConditionForLocalCategory = "ElectricCurrent3"
	SensorMonitoringConditionForLocalCategoryElectricPower    SensorMonitoringConditionForLocalCategory = "ElectricPower"
	SensorMonitoringConditionForLocalCategoryEtc              SensorMonitoringConditionForLocalCategory = "Etc"
	SensorMonitoringConditionForLocalCategoryHumidity         SensorMonitoringConditionForLocalCategory = "Humidity"
	SensorMonitoringConditionForLocalCategoryPowerFactor      SensorMonitoringConditionForLocalCategory = "PowerFactor"
	SensorMonitoringConditionForLocalCategoryTemperature      SensorMonitoringConditionForLocalCategory = "Temperature"
	SensorMonitoringConditionForLocalCategoryVoltage1         SensorMonitoringConditionForLocalCategory = "Voltage1"
	SensorMonitoringConditionForLocalCategoryVoltage2         SensorMonitoringConditionForLocalCategory = "Voltage2"
	SensorMonitoringConditionForLocalCategoryVoltage3         SensorMonitoringConditionForLocalCategory = "Voltage3"
)

// BaseForLocal defines model for BaseForLocal.
type BaseForLocal struct {
	// CancellationElectricPower **復帰電力（kw）**
	CancellationElectricPower float32 `json:"cancellationElectricPower"`

	// ContractElectricPower **契約電力（kw）**
	ContractElectricPower float32 `json:"contractElectricPower"`

	// EnableStoppingIndoorFan **室内機ファンの停止設定**
	EnableStoppingIndoorFan bool `json:"enableStoppingIndoorFan"`

	// Equipments 機器のリスト
	Equipments []EquipmentForLocal `json:"equipments"`

	// Firmware ファームウェア
	Firmware *FirmwareForLocal `json:"firmware"`

	// Id **拠点識別**
	Id string `json:"id"`

	// InitialElectricPower **初期電力（kw）**
	InitialElectricPower float32 `json:"initialElectricPower"`

	// LimitElectricPower **限界電力（kw）**
	LimitElectricPower float32 `json:"limitElectricPower"`

	// Name **名称**
	Name string `json:"name"`

	// SendGridApiKey SendGridのAPIキー
	SendGridApiKey *string `json:"sendGridApiKey"`

	// SyncFrequency 同期頻度設定
	SyncFrequency SyncFrequencyForLocal `json:"syncFrequency"`

	// TargetElectricPower **目標電力（kw）**
	TargetElectricPower float32 `json:"targetElectricPower"`

	// Users アラート送信対象のユーザー
	Users []UserForLocal `json:"users"`
}

// ChildDeviceForLocal defines model for ChildDeviceForLocal.
type ChildDeviceForLocal struct {
	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// EnergySensors エネルギーセンサー
	EnergySensors []EnergySensorForLocal `json:"energySensors"`

	// EnvironmentalSensors 環境センサー
	EnvironmentalSensors []EnvironmentalSensorForLocal `json:"environmentalSensors"`

	// Id **子機識別**
	Id string `json:"id"`

	// InputContacts 入力接点
	InputContacts []InputContactForLocal `json:"inputContacts"`

	// Name **名称**
	Name string `json:"name"`

	// OutputContacts 出力接点
	OutputContacts []OutputContactForLocal `json:"outputContacts"`

	// ParentDeviceId **接続先（親機）**
	// 親機識別
	ParentDeviceId *string `json:"parentDeviceId"`

	// Wireless
	// **接続方法**
	// true: 無線
	// false: 有線
	Wireless bool `json:"wireless"`
}

// DemandControlOrderForLocal defines model for DemandControlOrderForLocal.
type DemandControlOrderForLocal struct {
	// Enabled **デマンド制御**
	// true: 制御　false: 制御しない
	Enabled bool `json:"enabled"`
}

// DemandPulseForLocal defines model for DemandPulseForLocal.
type DemandPulseForLocal struct {
	// AnomalyDurationSeconds **異常継続時間（秒）**
	AnomalyDurationSeconds int `json:"anomalyDurationSeconds"`

	// BatteryLevelNotificationThreshold 電池残量アラートのしきい値（％）
	// 値を下回った場合に発報
	BatteryLevelNotificationThreshold int `json:"batteryLevelNotificationThreshold"`

	// ConnectionId 接続先（ID）
	ConnectionId *int `json:"connectionId"`

	// DeviceName **デバイス名**
	DeviceName *string `json:"deviceName"`

	// ElectricEnergyPerPulse **１パルスあたりの電力量**
	ElectricEnergyPerPulse float32 `json:"electricEnergyPerPulse"`

	// Id **デマンドパルス識別**
	Id string `json:"id"`

	// Message **メッセージ**
	Message string `json:"message"`

	// Name **名称**
	Name string `json:"name"`

	// NotificationEnabled デマンドパルスの電池残量アラート通知 ON/OFF
	// true: ON
	// false: OFF
	NotificationEnabled bool `json:"notificationEnabled"`
}

// EnergySensorForLocal defines model for EnergySensorForLocal.
type EnergySensorForLocal struct {
	// ChildDeviceId **接続先（子機）**
	// 子機識別
	ChildDeviceId *string `json:"childDeviceId"`

	// ConnectionChannel 接続先（Channel）
	ConnectionChannel *int `json:"connectionChannel"`

	// ConnectionId 接続先（ID）
	ConnectionId *int `json:"connectionId"`

	// CoolingRatedElectricPowerConsumption **定格消費電力（冷房）（w）**
	CoolingRatedElectricPowerConsumption float32 `json:"coolingRatedElectricPowerConsumption"`

	// DeviceName **デバイス名**
	DeviceName *string `json:"deviceName"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// HeatingRatedElectricPowerConsumption **定格消費電力（暖房）（w）**
	HeatingRatedElectricPowerConsumption float32 `json:"heatingRatedElectricPowerConsumption"`

	// Id **エネルギーセンサー識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`

	// PowerFactor **力率**
	PowerFactor *float32 `json:"powerFactor"`

	// SensorMonitoringConditions 監視条件のリスト
	// 同期リクエスト時点で有効な監視条件のリストを返します
	SensorMonitoringConditions []SensorMonitoringConditionForLocal `json:"sensorMonitoringConditions"`

	// Voltage **電圧**
	Voltage *float32 `json:"voltage"`
}

// EnvironmentalSensorForLocal defines model for EnvironmentalSensorForLocal.
type EnvironmentalSensorForLocal struct {
	// Category **機器カテゴリ**
	// Temperature: 温度
	// Humidity: 湿度
	Category EnvironmentalSensorForLocalCategory `json:"category"`

	// ChildDeviceId **接続先（子機）**
	// 子機識別
	ChildDeviceId *string `json:"childDeviceId"`

	// ConnectionChannel 接続先（Channel）
	ConnectionChannel *int `json:"connectionChannel"`

	// ConnectionId 接続先（ID）
	ConnectionId *int `json:"connectionId"`

	// CorrectionAmount **補正量（℃）**
	CorrectionAmount *float32 `json:"correctionAmount"`

	// CorrectionRatio **補正倍率**
	CorrectionRatio *float32 `json:"correctionRatio"`

	// DeviceName **デバイス名**
	DeviceName *string `json:"deviceName"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// Id **環境センサー識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`

	// SensorMonitoringConditions 監視条件のリスト
	// 同期リクエスト時点で有効な監視条件のリストを返します
	SensorMonitoringConditions []SensorMonitoringConditionForLocal `json:"sensorMonitoringConditions"`
}

// EnvironmentalSensorForLocalCategory **機器カテゴリ**
// Temperature: 温度
// Humidity: 湿度
type EnvironmentalSensorForLocalCategory string

// EquipmentControlConditionForLocal defines model for EquipmentControlConditionForLocal.
type EquipmentControlConditionForLocal struct {
	// ControlEndDiscomfortIndex **制御終了不快指数**
	ControlEndDiscomfortIndex *float32 `json:"controlEndDiscomfortIndex"`

	// ControlEndHumidity **制御終了湿度**
	ControlEndHumidity *float32 `json:"controlEndHumidity"`

	// ControlEndTemperature **制御開始温度**
	ControlEndTemperature *float32 `json:"controlEndTemperature"`

	// ControlReleaseSeconds **制御解除時間**
	ControlReleaseSeconds float32 `json:"controlReleaseSeconds"`

	// ControlSeconds **制御時間**
	ControlSeconds float32 `json:"controlSeconds"`

	// ControlStartDiscomfortIndex **制御開始不快指数**
	ControlStartDiscomfortIndex *float32 `json:"controlStartDiscomfortIndex"`

	// ControlStartHumidity **制御開始湿度**
	ControlStartHumidity *float32 `json:"controlStartHumidity"`

	// ControlStartTemperature **制御開始温度**
	ControlStartTemperature *float32 `json:"controlStartTemperature"`

	// ControlTarget **制御対象**
	ControlTarget bool `json:"controlTarget"`

	// DemandControlEndDiscomfortIndex **デマンド制御終了不快指数**
	DemandControlEndDiscomfortIndex *float32 `json:"demandControlEndDiscomfortIndex"`

	// DemandControlEndHumidity **デマンド制御終了湿度**
	DemandControlEndHumidity *float32 `json:"demandControlEndHumidity"`

	// DemandControlEndTemperature **デマンド制御終了温度**
	DemandControlEndTemperature *float32 `json:"demandControlEndTemperature"`

	// DemandControlStartDiscomfortIndex **デマンド制御開始不快指数**
	DemandControlStartDiscomfortIndex *float32 `json:"demandControlStartDiscomfortIndex"`

	// DemandControlStartHumidity **デマンド制御開始湿度**
	DemandControlStartHumidity *float32 `json:"demandControlStartHumidity"`

	// DemandControlStartTemperature **デマンド制御開始温度**
	DemandControlStartTemperature *float32 `json:"demandControlStartTemperature"`

	// DemandControlTarget **デマンド制御対象**
	DemandControlTarget bool `json:"demandControlTarget"`

	// EquipmentId **機器識別**
	EquipmentId *string `json:"equipmentId"`

	// Name **名称**
	Name string `json:"name"`
}

// EquipmentForLocal defines model for EquipmentForLocal.
type EquipmentForLocal struct {
	// CapacityControlOutputContact **制御接点（容量）**
	CapacityControlOutputContact *OutputContactForLocal `json:"capacityControlOutputContact"`

	// DefrostControlOutputContact **デフロスト制御接点**
	DefrostControlOutputContact *OutputContactForLocal `json:"defrostControlOutputContact"`

	// EnergySensor **エネルギーセンサー**
	EnergySensor *EnergySensorForLocal `json:"energySensor"`

	// EnvironmentalSensors **環境センサー**
	EnvironmentalSensors []EnvironmentalSensorForLocal `json:"environmentalSensors"`

	// EquipmentControlCondition **制御条件**
	// 同期リクエスト時点で有効な制御条件を返します
	EquipmentControlCondition *EquipmentControlConditionForLocal `json:"equipmentControlCondition"`

	// Id **機器識別**
	Id string `json:"id"`

	// InputContact **デフロスト入力接点**
	InputContact *InputContactForLocal `json:"inputContact"`

	// InsideAirFanSensor **室内機ファンセンサー**
	InsideAirFanSensor *InsideAirFanSensorForLocal `json:"insideAirFanSensor"`

	// IntermittentControlOutputContact **制御接点（間欠）**
	IntermittentControlOutputContact *OutputContactForLocal `json:"intermittentControlOutputContact"`

	// JudgmentCriteria 判断基準
	// Max: 最大
	// Min: 最小
	// Average: 平均
	JudgmentCriteria EquipmentForLocalJudgmentCriteria `json:"judgmentCriteria"`

	// Mode **冷暖モード**
	// Auto: 自動
	// Cooling: 冷房のみ
	// Heating: 暖房のみ
	Mode EquipmentForLocalMode `json:"mode"`

	// Name **名称**
	Name string `json:"name"`

	// OperationJudgmentElectricPower **稼働判断電力（w）**
	OperationJudgmentElectricPower float32 `json:"operationJudgmentElectricPower"`

	// RequiredOperatingTime **稼働必須時間**（秒）
	RequiredOperatingTime int `json:"requiredOperatingTime"`
}

// EquipmentForLocalJudgmentCriteria 判断基準
// Max: 最大
// Min: 最小
// Average: 平均
type EquipmentForLocalJudgmentCriteria string

// EquipmentForLocalMode **冷暖モード**
// Auto: 自動
// Cooling: 冷房のみ
// Heating: 暖房のみ
type EquipmentForLocalMode string

// FirmwareForLocal defines model for FirmwareForLocal.
type FirmwareForLocal struct {
	// Name ファームウェアファイルの名前
	Name string `json:"name"`

	// Url ファームウェアファイルのURL（1時間有効）
	Url string `json:"url"`
}

// InputContactForLocal defines model for InputContactForLocal.
type InputContactForLocal struct {
	// Category **入力カテゴリ**
	// Defrost: デフロスト
	// Breaker: ブレーカー
	// Etc: その他
	Category InputContactForLocalCategory `json:"category"`

	// ChildDeviceId **接続先（子機）**
	// 子機識別
	ChildDeviceId *string `json:"childDeviceId"`

	// ConnectionChannel 接続先（Channel）
	ConnectionChannel *int `json:"connectionChannel"`

	// ConnectionId 接続先（ID）
	ConnectionId *int `json:"connectionId"`

	// DeviceName **デバイス名**
	DeviceName *string `json:"deviceName"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// Id **入力接点識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`

	// SensorMonitoringConditions 監視条件のリスト
	// 同期リクエスト時点で有効な監視条件のリストを返します
	SensorMonitoringConditions []SensorMonitoringConditionForLocal `json:"sensorMonitoringConditions"`
}

// InputContactForLocalCategory **入力カテゴリ**
// Defrost: デフロスト
// Breaker: ブレーカー
// Etc: その他
type InputContactForLocalCategory string

// InsideAirFanSensorForLocal defines model for InsideAirFanSensorForLocal.
type InsideAirFanSensorForLocal struct {
	// ControlElectricCurrent **制御時電流**
	ControlElectricCurrent float32 `json:"controlElectricCurrent"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// Id **室内機ファンセンサー識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`

	// OperatingElectricCurrent **稼働時電流**
	OperatingElectricCurrent float32 `json:"operatingElectricCurrent"`

	// PowerFactor **力率**
	PowerFactor float32 `json:"powerFactor"`

	// RatedElectricPowerConsumption **定格電力（w）**
	RatedElectricPowerConsumption float32 `json:"ratedElectricPowerConsumption"`

	// Voltage **電圧**
	Voltage float32 `json:"voltage"`
}

// ManualControlOrderForLocal defines model for ManualControlOrderForLocal.
type ManualControlOrderForLocal struct {
	// Enabled **制御命令**
	// true: 制御
	// false: 制御解除
	Enabled bool `json:"enabled"`

	// EquipmentId **機器識別**
	EquipmentId string `json:"equipmentId"`
}

// ManualControlOrderResultForLocal defines model for ManualControlOrderResultForLocal.
type ManualControlOrderResultForLocal struct {
	// Succeeded 処理が成功したかどうか
	// 更新対象がない場合もtrue（成功）を返す
	// 例. 先に手動で命令が取り消された、機器のIDを間違えている
	// true: 成功
	// false: 失敗
	Succeeded bool `json:"succeeded"`
}

// ManualDefrostOrderForLocal defines model for ManualDefrostOrderForLocal.
type ManualDefrostOrderForLocal struct {
	// Enabled **停止命令**
	// true: 停止
	// false: 停止解除
	Enabled bool `json:"enabled"`

	// OutputContactId **出力接点識別**
	OutputContactId string `json:"outputContactId"`
}

// OutputContactForLocal defines model for OutputContactForLocal.
type OutputContactForLocal struct {
	// Category **出力カテゴリ**
	// Control: 制御
	// DefrostControl: デフロスト制御
	Category OutputContactForLocalCategory `json:"category"`

	// ChildDeviceId **接続先（子機）**
	// 子機識別
	ChildDeviceId *string `json:"childDeviceId"`

	// ConnectionChannel 接続先（Channel）
	ConnectionChannel *int `json:"connectionChannel"`

	// ConnectionId 接続先（ID）
	ConnectionId *int `json:"connectionId"`

	// ControlMethod **制御方法**
	ControlMethod OutputContactForLocalControlMethod `json:"controlMethod"`

	// DeviceName **デバイス名**
	DeviceName *string `json:"deviceName"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// Id **出力接点識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`

	// SensorMonitoringConditions 監視条件のリスト
	// 同期リクエスト時点で有効な監視条件のリストを返します
	SensorMonitoringConditions []SensorMonitoringConditionForLocal `json:"sensorMonitoringConditions"`
}

// OutputContactForLocalCategory **出力カテゴリ**
// Control: 制御
// DefrostControl: デフロスト制御
type OutputContactForLocalCategory string

// OutputContactForLocalControlMethod **制御方法**
type OutputContactForLocalControlMethod string

// ParentDeviceForLocal defines model for ParentDeviceForLocal.
type ParentDeviceForLocal struct {
	// Base 拠点
	Base BaseForLocal `json:"base"`

	// ChildDevices 子機のリスト
	ChildDevices []ChildDeviceForLocal `json:"childDevices"`

	// DemandPulse デマンドパルス
	DemandPulse *DemandPulseForLocal `json:"demandPulse"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// Id **親機識別**
	Id string `json:"id"`

	// Name **名称**
	Name string `json:"name"`
}

// ParentDeviceRestartOrderForLocal defines model for ParentDeviceRestartOrderForLocal.
type ParentDeviceRestartOrderForLocal struct {
	// Enabled **主装置再起動**
	// true: 再起動
	Enabled bool `json:"enabled"`
}

// ParentDeviceRestartOrderResultForLocal defines model for ParentDeviceRestartOrderResultForLocal.
type ParentDeviceRestartOrderResultForLocal struct {
	// Succeeded 処理が成功したかどうか
	// 更新対象がない場合もtrue（成功）を返す
	// 例. 先に手動で命令が取り消された、親機のIDを間違えている
	// true: 成功
	// false: 失敗
	Succeeded bool `json:"succeeded"`
}

// SensorMonitoringConditionForLocal defines model for SensorMonitoringConditionForLocal.
type SensorMonitoringConditionForLocal struct {
	// AnomalyDurationSeconds **異常継続時間（秒）**
	AnomalyDurationSeconds int `json:"anomalyDurationSeconds"`

	// AnomalyType **異常判断**
	// More: 上回り
	// Less: 下回り
	// ON: ON
	// OFF: OFF
	AnomalyType SensorMonitoringConditionForLocalAnomalyType `json:"anomalyType"`

	// Category **監視対象カテゴリ**
	// ElectricCurrent1: 電流1（A）
	// ElectricCurrent2: 電流2（A）
	// ElectricCurrent3: 電流3（A）
	// Voltage1: 電圧1（V）
	// Voltage2: 電圧2（V）
	// Voltage3: 電圧3（V）
	// PowerFactor: 力率
	// ElectricPower: 電力（W）
	// Temperature: 温度（℃）
	// Humidity: 湿度（％）
	// DiscomfortIndex: 不快指数（DI）
	// BatteryLevel: 電池残量
	// Breaker: ブレーカー遮断
	// Control: 制御ONOFF（秒）
	// Etc:その他
	Category SensorMonitoringConditionForLocalCategory `json:"category"`

	// Enabled **有効**
	Enabled bool `json:"enabled"`

	// EnergySensorId **エネルギーセンサー識別**
	EnergySensorId *string `json:"energySensorId"`

	// EnvironmentalSensorId **環境センサー識別**
	EnvironmentalSensorId *string `json:"environmentalSensorId"`

	// Id **センサー監視識別**
	Id string `json:"id"`

	// InputContactId **入力接点識別**
	InputContactId *string `json:"inputContactId"`

	// Message **メッセージ**
	Message string `json:"message"`

	// Name **名称**
	Name string `json:"name"`

	// OutputContactId **出力接点識別**
	OutputContactId *string `json:"outputContactId"`

	// Threshold **閾値**
	Threshold float32 `json:"threshold"`
}

// SensorMonitoringConditionForLocalAnomalyType **異常判断**
// More: 上回り
// Less: 下回り
// ON: ON
// OFF: OFF
type SensorMonitoringConditionForLocalAnomalyType string

// SensorMonitoringConditionForLocalCategory **監視対象カテゴリ**
// ElectricCurrent1: 電流1（A）
// ElectricCurrent2: 電流2（A）
// ElectricCurrent3: 電流3（A）
// Voltage1: 電圧1（V）
// Voltage2: 電圧2（V）
// Voltage3: 電圧3（V）
// PowerFactor: 力率
// ElectricPower: 電力（W）
// Temperature: 温度（℃）
// Humidity: 湿度（％）
// DiscomfortIndex: 不快指数（DI）
// BatteryLevel: 電池残量
// Breaker: ブレーカー遮断
// Control: 制御ONOFF（秒）
// Etc:その他
type SensorMonitoringConditionForLocalCategory string

// SyncFrequencyForLocal defines model for SyncFrequencyForLocal.
type SyncFrequencyForLocal struct {
	// DemandControlOrder デマンド制御命令の同期頻度（秒）
	DemandControlOrder int `json:"demandControlOrder"`

	// ManualControlOrder 緊急制御命令の同期頻度（秒）
	ManualControlOrder int `json:"manualControlOrder"`

	// ManualDefrostOrder 緊急デフロスト命令の同期頻度（秒）
	ManualDefrostOrder int `json:"manualDefrostOrder"`

	// MasterData マスターデータの同期頻度（秒）
	MasterData int `json:"masterData"`

	// ParentDeviceRestartOrder 親機再起動の同期頻度（秒）
	ParentDeviceRestartOrder int `json:"parentDeviceRestartOrder"`
}

// UserForLocal defines model for UserForLocal.
type UserForLocal struct {
	// Email メールアドレス
	Email string `json:"email"`

	// EnableBatteryAlert 電池残量アラートをメール通知するかどうか
	EnableBatteryAlert bool `json:"enableBatteryAlert"`

	// EnableConnectionAlert 通信アラートをメール通知するかどうか
	EnableConnectionAlert bool `json:"enableConnectionAlert"`

	// EnableDemandAlert デマンドアラートをメール通知するかどうか
	EnableDemandAlert bool `json:"enableDemandAlert"`

	// EnableSensorAlert センサー監視アラートをメール通知するかどうか
	EnableSensorAlert bool `json:"enableSensorAlert"`

	// EnableSystemAlert 親機システムアラートをメール通知するかどうか
	EnableSystemAlert bool `json:"enableSystemAlert"`

	// EnableUpsAlert 親機電源アラートをメール通知するかどうか
	EnableUpsAlert bool `json:"enableUpsAlert"`
}
