// Package syncapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.1 DO NOT EDIT.
package syncapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// BasesControllerGetDemandControlOrder request
	BasesControllerGetDemandControlOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BasesControllerGetManualControlOrders request
	BasesControllerGetManualControlOrders(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BasesControllerGetManualDefrostOrders request
	BasesControllerGetManualDefrostOrders(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EquipmentsControllerReleaseManualControlOrder request
	EquipmentsControllerReleaseManualControlOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParentDevicesControllerGetParentDevice request
	ParentDevicesControllerGetParentDevice(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParentDevicesControllerGetParentDeviceRestartOrder request
	ParentDevicesControllerGetParentDeviceRestartOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParentDevicesControllerCompleteParentDeviceRestart request
	ParentDevicesControllerCompleteParentDeviceRestart(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) BasesControllerGetDemandControlOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBasesControllerGetDemandControlOrderRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BasesControllerGetManualControlOrders(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBasesControllerGetManualControlOrdersRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BasesControllerGetManualDefrostOrders(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBasesControllerGetManualDefrostOrdersRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EquipmentsControllerReleaseManualControlOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEquipmentsControllerReleaseManualControlOrderRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParentDevicesControllerGetParentDevice(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParentDevicesControllerGetParentDeviceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParentDevicesControllerGetParentDeviceRestartOrder(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParentDevicesControllerGetParentDeviceRestartOrderRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParentDevicesControllerCompleteParentDeviceRestart(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParentDevicesControllerCompleteParentDeviceRestartRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBasesControllerGetDemandControlOrderRequest generates requests for BasesControllerGetDemandControlOrder
func NewBasesControllerGetDemandControlOrderRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/bases/%s/demand-control-order", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBasesControllerGetManualControlOrdersRequest generates requests for BasesControllerGetManualControlOrders
func NewBasesControllerGetManualControlOrdersRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/bases/%s/manual-control-orders", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBasesControllerGetManualDefrostOrdersRequest generates requests for BasesControllerGetManualDefrostOrders
func NewBasesControllerGetManualDefrostOrdersRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/bases/%s/manual-defrost-orders", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEquipmentsControllerReleaseManualControlOrderRequest generates requests for EquipmentsControllerReleaseManualControlOrder
func NewEquipmentsControllerReleaseManualControlOrderRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/equipments/%s/released", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewParentDevicesControllerGetParentDeviceRequest generates requests for ParentDevicesControllerGetParentDevice
func NewParentDevicesControllerGetParentDeviceRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/parent-devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewParentDevicesControllerGetParentDeviceRestartOrderRequest generates requests for ParentDevicesControllerGetParentDeviceRestartOrder
func NewParentDevicesControllerGetParentDeviceRestartOrderRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/parent-devices/%s/parent-device-restart-order", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewParentDevicesControllerCompleteParentDeviceRestartRequest generates requests for ParentDevicesControllerCompleteParentDeviceRestart
func NewParentDevicesControllerCompleteParentDeviceRestartRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/parent-devices/%s/restarted", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BasesControllerGetDemandControlOrder request
	BasesControllerGetDemandControlOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetDemandControlOrderResponse, error)

	// BasesControllerGetManualControlOrders request
	BasesControllerGetManualControlOrdersWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetManualControlOrdersResponse, error)

	// BasesControllerGetManualDefrostOrders request
	BasesControllerGetManualDefrostOrdersWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetManualDefrostOrdersResponse, error)

	// EquipmentsControllerReleaseManualControlOrder request
	EquipmentsControllerReleaseManualControlOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*EquipmentsControllerReleaseManualControlOrderResponse, error)

	// ParentDevicesControllerGetParentDevice request
	ParentDevicesControllerGetParentDeviceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerGetParentDeviceResponse, error)

	// ParentDevicesControllerGetParentDeviceRestartOrder request
	ParentDevicesControllerGetParentDeviceRestartOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerGetParentDeviceRestartOrderResponse, error)

	// ParentDevicesControllerCompleteParentDeviceRestart request
	ParentDevicesControllerCompleteParentDeviceRestartWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerCompleteParentDeviceRestartResponse, error)
}

type BasesControllerGetDemandControlOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DemandControlOrderForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r BasesControllerGetDemandControlOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BasesControllerGetDemandControlOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BasesControllerGetManualControlOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ManualControlOrderForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r BasesControllerGetManualControlOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BasesControllerGetManualControlOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BasesControllerGetManualDefrostOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ManualDefrostOrderForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r BasesControllerGetManualDefrostOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BasesControllerGetManualDefrostOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EquipmentsControllerReleaseManualControlOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ManualControlOrderResultForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r EquipmentsControllerReleaseManualControlOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EquipmentsControllerReleaseManualControlOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParentDevicesControllerGetParentDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ParentDeviceForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ParentDevicesControllerGetParentDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParentDevicesControllerGetParentDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParentDevicesControllerGetParentDeviceRestartOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ParentDeviceRestartOrderForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ParentDevicesControllerGetParentDeviceRestartOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParentDevicesControllerGetParentDeviceRestartOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParentDevicesControllerCompleteParentDeviceRestartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ParentDeviceRestartOrderResultForLocal
	JSON403      *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（403）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON404 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（404）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON500 *struct {
		// Path リクエストパス
		Path *string `json:"path,omitempty"`

		// StatusCode HTTPステータスコード（500）
		StatusCode *int `json:"statusCode,omitempty"`

		// Timestamp ISO8601形式の日時文字列
		Timestamp *string `json:"timestamp,omitempty"`
	}
	JSON503 *struct {
		// Message エラーメッセージ
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ParentDevicesControllerCompleteParentDeviceRestartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParentDevicesControllerCompleteParentDeviceRestartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// BasesControllerGetDemandControlOrderWithResponse request returning *BasesControllerGetDemandControlOrderResponse
func (c *ClientWithResponses) BasesControllerGetDemandControlOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetDemandControlOrderResponse, error) {
	rsp, err := c.BasesControllerGetDemandControlOrder(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBasesControllerGetDemandControlOrderResponse(rsp)
}

// BasesControllerGetManualControlOrdersWithResponse request returning *BasesControllerGetManualControlOrdersResponse
func (c *ClientWithResponses) BasesControllerGetManualControlOrdersWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetManualControlOrdersResponse, error) {
	rsp, err := c.BasesControllerGetManualControlOrders(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBasesControllerGetManualControlOrdersResponse(rsp)
}

// BasesControllerGetManualDefrostOrdersWithResponse request returning *BasesControllerGetManualDefrostOrdersResponse
func (c *ClientWithResponses) BasesControllerGetManualDefrostOrdersWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*BasesControllerGetManualDefrostOrdersResponse, error) {
	rsp, err := c.BasesControllerGetManualDefrostOrders(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBasesControllerGetManualDefrostOrdersResponse(rsp)
}

// EquipmentsControllerReleaseManualControlOrderWithResponse request returning *EquipmentsControllerReleaseManualControlOrderResponse
func (c *ClientWithResponses) EquipmentsControllerReleaseManualControlOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*EquipmentsControllerReleaseManualControlOrderResponse, error) {
	rsp, err := c.EquipmentsControllerReleaseManualControlOrder(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEquipmentsControllerReleaseManualControlOrderResponse(rsp)
}

// ParentDevicesControllerGetParentDeviceWithResponse request returning *ParentDevicesControllerGetParentDeviceResponse
func (c *ClientWithResponses) ParentDevicesControllerGetParentDeviceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerGetParentDeviceResponse, error) {
	rsp, err := c.ParentDevicesControllerGetParentDevice(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParentDevicesControllerGetParentDeviceResponse(rsp)
}

// ParentDevicesControllerGetParentDeviceRestartOrderWithResponse request returning *ParentDevicesControllerGetParentDeviceRestartOrderResponse
func (c *ClientWithResponses) ParentDevicesControllerGetParentDeviceRestartOrderWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerGetParentDeviceRestartOrderResponse, error) {
	rsp, err := c.ParentDevicesControllerGetParentDeviceRestartOrder(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParentDevicesControllerGetParentDeviceRestartOrderResponse(rsp)
}

// ParentDevicesControllerCompleteParentDeviceRestartWithResponse request returning *ParentDevicesControllerCompleteParentDeviceRestartResponse
func (c *ClientWithResponses) ParentDevicesControllerCompleteParentDeviceRestartWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ParentDevicesControllerCompleteParentDeviceRestartResponse, error) {
	rsp, err := c.ParentDevicesControllerCompleteParentDeviceRestart(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParentDevicesControllerCompleteParentDeviceRestartResponse(rsp)
}

// ParseBasesControllerGetDemandControlOrderResponse parses an HTTP response from a BasesControllerGetDemandControlOrderWithResponse call
func ParseBasesControllerGetDemandControlOrderResponse(rsp *http.Response) (*BasesControllerGetDemandControlOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BasesControllerGetDemandControlOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DemandControlOrderForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseBasesControllerGetManualControlOrdersResponse parses an HTTP response from a BasesControllerGetManualControlOrdersWithResponse call
func ParseBasesControllerGetManualControlOrdersResponse(rsp *http.Response) (*BasesControllerGetManualControlOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BasesControllerGetManualControlOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ManualControlOrderForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseBasesControllerGetManualDefrostOrdersResponse parses an HTTP response from a BasesControllerGetManualDefrostOrdersWithResponse call
func ParseBasesControllerGetManualDefrostOrdersResponse(rsp *http.Response) (*BasesControllerGetManualDefrostOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BasesControllerGetManualDefrostOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ManualDefrostOrderForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseEquipmentsControllerReleaseManualControlOrderResponse parses an HTTP response from a EquipmentsControllerReleaseManualControlOrderWithResponse call
func ParseEquipmentsControllerReleaseManualControlOrderResponse(rsp *http.Response) (*EquipmentsControllerReleaseManualControlOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EquipmentsControllerReleaseManualControlOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManualControlOrderResultForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseParentDevicesControllerGetParentDeviceResponse parses an HTTP response from a ParentDevicesControllerGetParentDeviceWithResponse call
func ParseParentDevicesControllerGetParentDeviceResponse(rsp *http.Response) (*ParentDevicesControllerGetParentDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParentDevicesControllerGetParentDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ParentDeviceForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseParentDevicesControllerGetParentDeviceRestartOrderResponse parses an HTTP response from a ParentDevicesControllerGetParentDeviceRestartOrderWithResponse call
func ParseParentDevicesControllerGetParentDeviceRestartOrderResponse(rsp *http.Response) (*ParentDevicesControllerGetParentDeviceRestartOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParentDevicesControllerGetParentDeviceRestartOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ParentDeviceRestartOrderForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseParentDevicesControllerCompleteParentDeviceRestartResponse parses an HTTP response from a ParentDevicesControllerCompleteParentDeviceRestartWithResponse call
func ParseParentDevicesControllerCompleteParentDeviceRestartResponse(rsp *http.Response) (*ParentDevicesControllerCompleteParentDeviceRestartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParentDevicesControllerCompleteParentDeviceRestartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ParentDeviceRestartOrderResultForLocal
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（403）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（404）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Path リクエストパス
			Path *string `json:"path,omitempty"`

			// StatusCode HTTPステータスコード（500）
			StatusCode *int `json:"statusCode,omitempty"`

			// Timestamp ISO8601形式の日時文字列
			Timestamp *string `json:"timestamp,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Message エラーメッセージ
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
