package app

import (
	"context"
	"encoding/json"
	"etos-mainunit/measureapi"
	"etos-mainunit/syncapi"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// 親機データ取得用タイムアウト値
// 128KB以内のデータを想定
// 128 KB(1024 Kbit) / (128 kbps * 0.8(伝送効率) ) = 10 (sec)
const cloudTimeoutSecond10s = 10 * time.Second
const cloudTimeoutSecond20s = 20 * time.Second
const cloudTimeoutSecond30s = 30 * time.Second

// その他のデータ取得、設定用タイムアウト値
// 8KB以内のデータを想定
// 8 KB(64 Kbit) / (128 kbps * 0.8(伝送効率) ) = 0.625 (sec)
const cloudTimeoutSecond1s = 1 * time.Second
const cloudTimeoutSecond3s = 3 * time.Second
const cloudTimeoutSecond5s = 5 * time.Second

func MeasureAddXApiKey(env Env) func(ctx context.Context, req *http.Request) error {
	return func(ctx context.Context, req *http.Request) error {
		// 認証ヘッダーの設定
		apiKey := env.MeasureServerAPIKey
		authorizerName := env.MeasureServerAmzCustomauthorizerName

		// デバッグログ（機密情報は一部のみ表示）
		// apiKeyPrefix := ""
		// if len(apiKey) > 0 {
		// 	if len(apiKey) > 8 {
		// 		apiKeyPrefix = apiKey[:8] + "..."
		// 	} else {
		// 		apiKeyPrefix = "***"
		// 	}
		// }
		// Logger.Writef(LOG_LEVEL_DEBUG, "MeasureAddXApiKey: x-api-key length=%d, prefix=%s, x-amz-customauthorizer-name=%s",
		// 	len(apiKey), apiKeyPrefix, authorizerName)

		// 認証情報の検証
		if apiKey == "" {
			Logger.Writef(LOG_LEVEL_ERR, "MeasureAddXApiKey: MeasureServerAPIKey is empty")
			return fmt.Errorf("MeasureServerAPIKey is empty")
		}
		if authorizerName == "" {
			Logger.Writef(LOG_LEVEL_ERR, "MeasureAddXApiKey: MeasureServerAmzCustomauthorizerName is empty")
			return fmt.Errorf("MeasureServerAmzCustomauthorizerName is empty")
		}

		req.Header.Add("x-api-key", apiKey)
		req.Header.Add("x-amz-customauthorizer-name", authorizerName)
		return nil
	}
}

func SyncAddXApiKey(env Env) func(ctx context.Context, req *http.Request) error {
	return func(ctx context.Context, req *http.Request) error {
		req.Header.Add("x-api-key", env.SyncServerAPIKey)
		return nil
	}
}

// AutoGenerated APIから取得した親機データを格納する構造体
type AutoGenerated struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
	Base    struct {
		ID                        string  `json:"id"`
		Name                      string  `json:"name"`
		ContractElectricPower     float64 `json:"contractElectricPower"`
		LimitElectricPower        float64 `json:"limitElectricPower"`
		TargetElectricPower       float64 `json:"targetElectricPower"`
		CancellationElectricPower float64 `json:"cancellationElectricPower"`
		InitialElectricPower      float64 `json:"initialElectricPower"`
		// EnableStoppingIndoorFan   bool    `json:"enableStoppingIndoorFan"`
		SendGridAPIKey string `json:"sendGridApiKey"`
		Equipments     []struct {
			ID                             string  `json:"id"`
			Name                           string  `json:"name"`
			OperationJudgmentElectricPower float64 `json:"operationJudgmentElectricPower"`
			RequiredOperatingTime          int64   `json:"requiredOperatingTime"`
			Mode                           string  `json:"mode"`
			JudgmentCriteria               string  `json:"judgmentCriteria"`
			EnergySensor                   struct {
				ID                                   string  `json:"id"`
				Name                                 string  `json:"name"`
				DeviceName                           string  `json:"deviceName"`
				Voltage                              float64 `json:"voltage"`
				PowerFactor                          float64 `json:"powerFactor"`
				CoolingRatedElectricPowerConsumption float64 `json:"coolingRatedElectricPowerConsumption"`
				HeatingRatedElectricPowerConsumption float64 `json:"heatingRatedElectricPowerConsumption"`
				Enabled                              bool    `json:"enabled"`
				ConnectionID                         int     `json:"connectionId"`
				ConnectionChannel                    int     `json:"connectionChannel"`
				ChildDeviceID                        string  `json:"childDeviceId"`
				SensorMonitoringConditions           []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"energySensor"`
			// EnergySensorGroup struct {
			// 	ID                         string `json:"id"`
			// 	Name                       string `json:"name"`
			// 	Enabled                    bool   `json:"enabled"`
			// 	SensorMonitoringConditions []struct {
			// 		ID                     string  `json:"id"`
			// 		Name                   string  `json:"name"`
			// 		AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
			// 		Message                string  `json:"message"`
			// 		Enabled                bool    `json:"enabled"`
			// 		Category               string  `json:"category"`
			// 		AnomalyType            string  `json:"anomalyType"`
			// 		Threshold              float64 `json:"threshold"`
			// 		EnergySensorID         string  `json:"energySensorId"`
			// 		EnergySensorGroupID    string  `json:"energySensorGroupId"`
			// 		EnvironmentalSensorID  string  `json:"environmentalSensorId"`
			// 		InputContactID         string  `json:"inputContactId"`
			// 		OutputContactID        string  `json:"outputContactId"`
			// 	} `json:"sensorMonitoringConditions"`
			// 	AdditionEnergySensors []struct {
			// 		ID                                   string  `json:"id"`
			// 		Name                                 string  `json:"name"`
			// 		DeviceName                           string  `json:"deviceName"`
			// 		Voltage                              float64 `json:"voltage"`
			// 		PowerFactor                          float64 `json:"powerFactor"`
			// 		CoolingRatedElectricPowerConsumption float64 `json:"coolingRatedElectricPowerConsumption"`
			// 		HeatingRatedElectricPowerConsumption float64 `json:"heatingRatedElectricPowerConsumption"`
			// 		Enabled                              bool    `json:"enabled"`
			// 		ConnectionID                         int     `json:"connectionId"`
			// 		ConnectionChannel                    int     `json:"connectionChannel"`
			// 		ChildDeviceID                        string  `json:"childDeviceId"`
			// 		SensorMonitoringConditions           []struct {
			// 			ID                     string  `json:"id"`
			// 			Name                   string  `json:"name"`
			// 			AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
			// 			Message                string  `json:"message"`
			// 			Enabled                bool    `json:"enabled"`
			// 			Category               string  `json:"category"`
			// 			AnomalyType            string  `json:"anomalyType"`
			// 			Threshold              float64 `json:"threshold"`
			// 			EnergySensorID         string  `json:"energySensorId"`
			// 			EnergySensorGroupID    string  `json:"energySensorGroupId"`
			// 			EnvironmentalSensorID  string  `json:"environmentalSensorId"`
			// 			InputContactID         string  `json:"inputContactId"`
			// 			OutputContactID        string  `json:"outputContactId"`
			// 		} `json:"sensorMonitoringConditions"`
			// 	} `json:"additionEnergySensors"`
			// 	SubtractionEnergySensors []struct {
			// 		ID                                   string  `json:"id"`
			// 		Name                                 string  `json:"name"`
			// 		DeviceName                           string  `json:"deviceName"`
			// 		Voltage                              float64 `json:"voltage"`
			// 		PowerFactor                          float64 `json:"powerFactor"`
			// 		CoolingRatedElectricPowerConsumption float64 `json:"coolingRatedElectricPowerConsumption"`
			// 		HeatingRatedElectricPowerConsumption float64 `json:"heatingRatedElectricPowerConsumption"`
			// 		Enabled                              bool    `json:"enabled"`
			// 		ConnectionID                         int     `json:"connectionId"`
			// 		ConnectionChannel                    int     `json:"connectionChannel"`
			// 		ChildDeviceID                        string  `json:"childDeviceId"`
			// 		SensorMonitoringConditions           []struct {
			// 			ID                     string  `json:"id"`
			// 			Name                   string  `json:"name"`
			// 			AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
			// 			Message                string  `json:"message"`
			// 			Enabled                bool    `json:"enabled"`
			// 			Category               string  `json:"category"`
			// 			AnomalyType            string  `json:"anomalyType"`
			// 			Threshold              float64 `json:"threshold"`
			// 			EnergySensorID         string  `json:"energySensorId"`
			// 			EnergySensorGroupID    string  `json:"energySensorGroupId"`
			// 			EnvironmentalSensorID  string  `json:"environmentalSensorId"`
			// 			InputContactID         string  `json:"inputContactId"`
			// 			OutputContactID        string  `json:"outputContactId"`
			// 		} `json:"sensorMonitoringConditions"`
			// 	} `json:"subtractionEnergySensors"`
			// } `json:"energySensorGroup"`
			InsideAirFanSensor struct {
				ID                            string  `json:"id"`
				Name                          string  `json:"name"`
				ControlElectricCurrent        float64 `json:"controlElectricCurrent"`
				OperatingElectricCurrent      float64 `json:"operatingElectricCurrent"`
				Voltage                       float64 `json:"voltage"`
				PowerFactor                   float64 `json:"powerFactor"`
				RatedElectricPowerConsumption float64 `json:"ratedElectricPowerConsumption"`
				Enabled                       bool    `json:"enabled"`
			} `json:"insideAirFanSensor"`
			EnvironmentalSensors []struct {
				ID                         string      `json:"id"`
				Name                       string      `json:"name"`
				DeviceName                 string      `json:"deviceName"`
				CorrectionAmount           NullFloat64 `json:"correctionAmount"`
				CorrectionRatio            NullFloat64 `json:"correctionRatio"`
				Enabled                    bool        `json:"enabled"`
				ConnectionID               int         `json:"connectionId"`
				ConnectionChannel          int         `json:"connectionChannel"`
				Category                   string      `json:"category"`
				ChildDeviceID              string      `json:"childDeviceId"`
				SensorMonitoringConditions []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"environmentalSensors"`
			InputContact struct {
				ID                         string `json:"id"`
				Name                       string `json:"name"`
				DeviceName                 string `json:"deviceName"`
				Enabled                    bool   `json:"enabled"`
				ConnectionID               int    `json:"connectionId"`
				ConnectionChannel          int    `json:"connectionChannel"`
				Category                   string `json:"category"`
				ChildDeviceID              string `json:"childDeviceId"`
				SensorMonitoringConditions []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"inputContact"`
			IntermittentControlOutputContact struct {
				ID                         string `json:"id"`
				Name                       string `json:"name"`
				DeviceName                 string `json:"deviceName"`
				ControlMethod              string `json:"controlMethod"`
				Enabled                    bool   `json:"enabled"`
				ConnectionID               int    `json:"connectionId"`
				ConnectionChannel          int    `json:"connectionChannel"`
				Category                   string `json:"category"`
				ChildDeviceID              string `json:"childDeviceId"`
				SensorMonitoringConditions []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"intermittentControlOutputContact"`
			CapacityControlOutputContact struct {
				ID                         string `json:"id"`
				Name                       string `json:"name"`
				DeviceName                 string `json:"deviceName"`
				ControlMethod              string `json:"controlMethod"`
				Enabled                    bool   `json:"enabled"`
				ConnectionID               int    `json:"connectionId"`
				ConnectionChannel          int    `json:"connectionChannel"`
				Category                   string `json:"category"`
				ChildDeviceID              string `json:"childDeviceId"`
				SensorMonitoringConditions []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"capacityControlOutputContact"`
			DefrostControlOutputContact struct {
				ID                         string `json:"id"`
				Name                       string `json:"name"`
				DeviceName                 string `json:"deviceName"`
				ControlMethod              string `json:"controlMethod"`
				Enabled                    bool   `json:"enabled"`
				ConnectionID               int    `json:"connectionId"`
				ConnectionChannel          int    `json:"connectionChannel"`
				Category                   string `json:"category"`
				ChildDeviceID              string `json:"childDeviceId"`
				SensorMonitoringConditions []struct {
					ID                     string  `json:"id"`
					Name                   string  `json:"name"`
					AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
					Message                string  `json:"message"`
					Enabled                bool    `json:"enabled"`
					Category               string  `json:"category"`
					AnomalyType            string  `json:"anomalyType"`
					Threshold              float64 `json:"threshold"`
					EnergySensorID         string  `json:"energySensorId"`
					// EnergySensorGroupID    string  `json:"energySensorGroupId"`
					EnvironmentalSensorID string `json:"environmentalSensorId"`
					InputContactID        string `json:"inputContactId"`
					OutputContactID       string `json:"outputContactId"`
				} `json:"sensorMonitoringConditions"`
			} `json:"defrostControlOutputContact"`
			EquipmentControlCondition struct {
				Name                              string      `json:"name"`
				ControlTarget                     bool        `json:"controlTarget"`
				DemandControlTarget               bool        `json:"demandControlTarget"`
				ControlSeconds                    int         `json:"controlSeconds"`
				ControlReleaseSeconds             int         `json:"controlReleaseSeconds"`
				ControlStartTemperature           NullFloat64 `json:"controlStartTemperature"`
				ControlEndTemperature             NullFloat64 `json:"controlEndTemperature"`
				ControlStartHumidity              NullFloat64 `json:"controlStartHumidity"`
				ControlEndHumidity                NullFloat64 `json:"controlEndHumidity"`
				ControlStartDiscomfortIndex       NullFloat64 `json:"controlStartDiscomfortIndex"`
				ControlEndDiscomfortIndex         NullFloat64 `json:"controlEndDiscomfortIndex"`
				DemandControlStartTemperature     NullFloat64 `json:"demandControlStartTemperature"`
				DemandControlEndTemperature       NullFloat64 `json:"demandControlEndTemperature"`
				DemandControlStartHumidity        NullFloat64 `json:"demandControlStartHumidity"`
				DemandControlEndHumidity          NullFloat64 `json:"demandControlEndHumidity"`
				DemandControlStartDiscomfortIndex NullFloat64 `json:"demandControlStartDiscomfortIndex"`
				DemandControlEndDiscomfortIndex   NullFloat64 `json:"demandControlEndDiscomfortIndex"`
				EquipmentID                       string      `json:"equipmentId"`
			} `json:"equipmentControlCondition"`
		} `json:"equipments"`
		SyncFrequency struct {
			MasterData               int `json:"masterData"`
			ManualControlOrder       int `json:"manualControlOrder"`
			ManualDefrostOrder       int `json:"manualDefrostOrder"`
			ParentDeviceRestartOrder int `json:"parentDeviceRestartOrder"`
			DemandControlOrder       int `json:"demandControlOrder"`
		} `json:"syncFrequency"`
		Firmware struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"firmware"`
		Users []struct {
			Email                 string `json:"email"`
			EnableBatteryAlert    bool   `json:"enableBatteryAlert"`
			EnableConnectionAlert bool   `json:"enableConnectionAlert"`
			EnableDemandAlert     bool   `json:"enableDemandAlert"`
			EnableSensorAlert     bool   `json:"enableSensorAlert"`
			EnableSystemAlert     bool   `json:"enableSystemAlert"`
			EnableUpsAlert        bool   `json:"enableUpsAlert"`
		} `json:"users"`
	} `json:"base"`
	ChildDevices []struct {
		ID             string `json:"id"`
		Name           string `json:"name"`
		Wireless       bool   `json:"wireless"`
		Enabled        bool   `json:"enabled"`
		ParentDeviceID string `json:"parentDeviceId"`
		EnergySensors  []struct {
			ID                                   string  `json:"id"`
			Name                                 string  `json:"name"`
			DeviceName                           string  `json:"deviceName"`
			Voltage                              float64 `json:"voltage"`
			PowerFactor                          float64 `json:"powerFactor"`
			CoolingRatedElectricPowerConsumption float64 `json:"coolingRatedElectricPowerConsumption"`
			HeatingRatedElectricPowerConsumption float64 `json:"heatingRatedElectricPowerConsumption"`
			Enabled                              bool    `json:"enabled"`
			ConnectionID                         int     `json:"connectionId"`
			ConnectionChannel                    int     `json:"connectionChannel"`
			ChildDeviceID                        string  `json:"childDeviceId"`
			SensorMonitoringConditions           []struct {
				ID                     string  `json:"id"`
				Name                   string  `json:"name"`
				AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
				Message                string  `json:"message"`
				Enabled                bool    `json:"enabled"`
				Category               string  `json:"category"`
				AnomalyType            string  `json:"anomalyType"`
				Threshold              float64 `json:"threshold"`
				EnergySensorID         string  `json:"energySensorId"`
				// EnergySensorGroupID    string  `json:"energySensorGroupId"`
				EnvironmentalSensorID string `json:"environmentalSensorId"`
				InputContactID        string `json:"inputContactId"`
				OutputContactID       string `json:"outputContactId"`
			} `json:"sensorMonitoringConditions"`
		} `json:"energySensors"`
		EnvironmentalSensors []struct {
			ID                         string      `json:"id"`
			Name                       string      `json:"name"`
			DeviceName                 string      `json:"deviceName"`
			CorrectionAmount           NullFloat64 `json:"correctionAmount"`
			CorrectionRatio            NullFloat64 `json:"correctionRatio"`
			Enabled                    bool        `json:"enabled"`
			ConnectionID               int         `json:"connectionId"`
			ConnectionChannel          int         `json:"connectionChannel"`
			Category                   string      `json:"category"`
			ChildDeviceID              string      `json:"childDeviceId"`
			SensorMonitoringConditions []struct {
				ID                     string  `json:"id"`
				Name                   string  `json:"name"`
				AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
				Message                string  `json:"message"`
				Enabled                bool    `json:"enabled"`
				Category               string  `json:"category"`
				AnomalyType            string  `json:"anomalyType"`
				Threshold              float64 `json:"threshold"`
				EnergySensorID         string  `json:"energySensorId"`
				// EnergySensorGroupID    string  `json:"energySensorGroupId"`
				EnvironmentalSensorID string `json:"environmentalSensorId"`
				InputContactID        string `json:"inputContactId"`
				OutputContactID       string `json:"outputContactId"`
			} `json:"sensorMonitoringConditions"`
		} `json:"environmentalSensors"`
		InputContacts []struct {
			ID                         string `json:"id"`
			Name                       string `json:"name"`
			DeviceName                 string `json:"deviceName"`
			Enabled                    bool   `json:"enabled"`
			ConnectionID               int    `json:"connectionId"`
			ConnectionChannel          int    `json:"connectionChannel"`
			Category                   string `json:"category"`
			ChildDeviceID              string `json:"childDeviceId"`
			SensorMonitoringConditions []struct {
				ID                     string  `json:"id"`
				Name                   string  `json:"name"`
				AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
				Message                string  `json:"message"`
				Enabled                bool    `json:"enabled"`
				Category               string  `json:"category"`
				AnomalyType            string  `json:"anomalyType"`
				Threshold              float64 `json:"threshold"`
				EnergySensorID         string  `json:"energySensorId"`
				// EnergySensorGroupID    string  `json:"energySensorGroupId"`
				EnvironmentalSensorID string `json:"environmentalSensorId"`
				InputContactID        string `json:"inputContactId"`
				OutputContactID       string `json:"outputContactId"`
			} `json:"sensorMonitoringConditions"`
		} `json:"inputContacts"`
		OutputContacts []struct {
			ID                         string `json:"id"`
			Name                       string `json:"name"`
			DeviceName                 string `json:"deviceName"`
			ControlMethod              string `json:"controlMethod"`
			Enabled                    bool   `json:"enabled"`
			ConnectionID               int    `json:"connectionId"`
			ConnectionChannel          int    `json:"connectionChannel"`
			Category                   string `json:"category"`
			ChildDeviceID              string `json:"childDeviceId"`
			SensorMonitoringConditions []struct {
				ID                     string  `json:"id"`
				Name                   string  `json:"name"`
				AnomalyDurationSeconds int     `json:"anomalyDurationSeconds"`
				Message                string  `json:"message"`
				Enabled                bool    `json:"enabled"`
				Category               string  `json:"category"`
				AnomalyType            string  `json:"anomalyType"`
				Threshold              float64 `json:"threshold"`
				EnergySensorID         string  `json:"energySensorId"`
				// EnergySensorGroupID    string  `json:"energySensorGroupId"`
				EnvironmentalSensorID string `json:"environmentalSensorId"`
				InputContactID        string `json:"inputContactId"`
				OutputContactID       string `json:"outputContactId"`
			} `json:"sensorMonitoringConditions"`
		} `json:"outputContacts"`
	} `json:"childDevices"`
	DemandPulse struct {
		ID                                string  `json:"id"`
		Name                              string  `json:"name"`
		DeviceName                        string  `json:"deviceName"`
		ElectricEnergyPerPulse            float64 `json:"electricEnergyPerPulse"`
		NotificationEnabled               bool    `json:"notificationEnabled"`
		BatteryLevelNotificationThreshold int     `json:"batteryLevelNotificationThreshold"`
		AnomalyDurationSeconds            int     `json:"anomalyDurationSeconds"`
		Message                           string  `json:"message"`
		ConnectionID                      int     `json:"connectionId"`
	} `json:"demandPulse"`
}

//========================================================================================================================
//	共通処理
//========================================================================================================================

// POST応答確認
func readPostResponse(res *http.Response) (measureapi.PostResponse, error) {
	var p measureapi.PostResponse

	// ステータスコードのチェック
	statusCode := res.StatusCode
	switch {
	case statusCode == http.StatusOK:
		// 200 OK: 正常なレスポンス
		b, err := io.ReadAll(res.Body)
		defer res.Body.Close()
		if err != nil {
			return p, err
		}

		if err := json.Unmarshal(b, &p); err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "readPostResponse JSON unmarshal error: %s, body: %s", err.Error(), string(b))
			return p, fmt.Errorf("JSON unmarshal error: %w", err)
		}

		return p, nil

	case statusCode == http.StatusBadRequest:
		// 400 Bad Request: リクエストエラー
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 400 Bad Request: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 400 Bad Request: invalid request")

	case statusCode == http.StatusUnauthorized:
		// 401 Unauthorized: 認証エラー
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 401 Unauthorized: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 401 Unauthorized: authentication failed")

	case statusCode == http.StatusForbidden:
		// 403 Forbidden: アクセス拒否
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 403 Forbidden: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case statusCode == http.StatusNotFound:
		// 404 Not Found: リソースが見つからない
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 404 Not Found: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 404 Not Found: resource not found")

	case statusCode == http.StatusInternalServerError:
		// 500 Internal Server Error: サーバーエラー
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 500 Internal Server Error: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case statusCode == http.StatusServiceUnavailable:
		// 503 Service Unavailable: サービス利用不可
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse HTTP 503 Service Unavailable: statusCode=%d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP 503 Service Unavailable: service unavailable")

	default:
		// その他のステータスコード
		b, _ := io.ReadAll(res.Body)
		defer res.Body.Close()
		Logger.Writef(LOG_LEVEL_ERR, "readPostResponse unexpected HTTP status: %d, body: %s", statusCode, string(b))
		return p, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}

// int8 を bool に変換
func i82b(i int8) bool {
	return i != 0
}

// bool を int8 に変換
func b2i8(b bool) int8 {
	if b {
		return 1
	}
	return 0
}

// CloudtoDatabase 構造体 -> database に変換
func CloudtoDatabase(d *AutoGenerated) {
	tx := database.GormDB.Begin()
	defer tx.Commit()

	// データベースのデータ削除
	deleteAllData(tx)

	// Logger.Writef(LOG_LEVEL_DEBUG, "====================BaseInformation=======================\n")
	if d.Base.ID != "" {
		// 拠点情報
		var baseInformation BaseInformation
		baseInformation.ID = d.Base.ID
		baseInformation.Name = d.Base.Name
		baseInformation.ContactElectricPower = float64(d.Base.ContractElectricPower)
		baseInformation.LimitElectricPower = float64(d.Base.LimitElectricPower)
		baseInformation.TargetElectricPower = float64(d.Base.TargetElectricPower)
		baseInformation.CancellationElectricPower = float64(d.Base.CancellationElectricPower)
		baseInformation.InitialElectricPower = float64(d.Base.InitialElectricPower)
		baseInformation.SendGridAPIKey = d.Base.SendGridAPIKey
		err := tx.Save(&baseInformation).Error
		if err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "BaseInformation Save DB : %+s", err.Error())
		} else {
			//			Logger.Writef(LOG_LEVEL_DEBUG, "BaseInformation Save DB : %+v", baseInformation)
		}

		// 更新周期サイクル
		var cycle UpdateCycle
		cycle.ID = d.Base.ID
		cycle.Master = int64(d.Base.SyncFrequency.MasterData)
		cycle.ManualControl = int64(d.Base.SyncFrequency.ManualControlOrder)
		cycle.Defrost = int64(d.Base.SyncFrequency.ManualDefrostOrder)
		cycle.Reboot = int64(d.Base.SyncFrequency.ParentDeviceRestartOrder)
		cycle.Demand = int64(d.Base.SyncFrequency.DemandControlOrder)
		err = tx.Save(&cycle).Error
		if err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "UpdateCycle Save DB : %+s", err.Error())
		} else {
			//			Logger.Writef(LOG_LEVEL_DEBUG, "UpdateCycle Save DB : %+v", cycle)
		}

		// メール宛先
		var mail UsersMailAddress
		for _, v := range d.Base.Users {
			mail.Email = v.Email
			mail.EnableBatteryAlert = b2i8(v.EnableBatteryAlert)
			mail.EnableConnectionAlert = b2i8(v.EnableConnectionAlert)
			mail.EnableDemandAlert = b2i8(v.EnableDemandAlert)
			mail.EnableSensorAlert = b2i8(v.EnableSensorAlert)
			mail.EnableSystemAlert = b2i8(v.EnableSystemAlert)
			mail.EnableUpsAlert = b2i8(v.EnableUpsAlert)
			err = tx.Save(&mail).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "UsersMailAddress Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "UsersMailAddress Save DB : %+v", mail)
			}
		}

		// ファームウェア情報
		var fw FirmwareUpdateInfo
		fw.Name = d.Base.Firmware.Name
		fw.URL = d.Base.Firmware.URL
		if (strings.Contains(fw.Name, "A9E") && MODEL == "A9E") || (strings.Contains(fw.Name, "G3L") && MODEL == "G3L") {
			err = tx.Save(&fw).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "FirmwareUpdateInfo Save DB : %+s", err.Error())
			} else {
				Logger.Writef(LOG_LEVEL_DEBUG, "FirmwareUpdateInfo Save DB : %+v", fw)
				if CurrentFWName != "" && CurrentFWName != fw.Name {
					FWUpdateFlag = true
					Logger.Writef(LOG_LEVEL_INFO, "FWUpdateFlag is true(CloudtoDatabase). Firmware is updated: %s -> %s", CurrentFWName, fw.Name)
				}
			}
		} else {
			Logger.Writef(LOG_LEVEL_INFO, "This firmware is not for %s: %s", MODEL, fw.Name)
		}
	}

	// Logger.Writef(LOG_LEVEL_DEBUG, "====================DeviceInformation=======================\n")
	for _, equipments := range d.Base.Equipments {
		if equipments.ID != "" {
			// デバイス識別子
			var deviceInformation DeviceInformation
			deviceInformation.ID = equipments.ID
			deviceInformation.Name = equipments.Name
			deviceInformation.Mode = equipments.Mode
			deviceInformation.StopElectricPower = float64(equipments.OperationJudgmentElectricPower)
			deviceInformation.RequiredControllingTime = int64(equipments.RequiredOperatingTime)
			deviceInformation.EnergySensorID = equipments.EnergySensor.ID
			deviceInformation.EnvironmentJudgmentCriteria = equipments.JudgmentCriteria
			deviceInformation.DefrostInputID = equipments.InputContact.ID
			deviceInformation.IntermittenControlContactID = equipments.IntermittentControlOutputContact.ID
			deviceInformation.CapacityControlContactID = equipments.CapacityControlOutputContact.ID
			deviceInformation.DefrostControlContactID = equipments.DefrostControlOutputContact.ID
			err := tx.Save(&deviceInformation).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "DeviceInformation Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "DeviceInformation Cloud Save DB : %+v", deviceInformation)
			}

			var e DeviceEnvironmentInformation
			e.DeviceID = equipments.ID
			for _, env := range equipments.EnvironmentalSensors {
				if env.ID != "" {
					e.SensorID = env.ID
					err := tx.Save(&e).Error
					if err != nil {
						Logger.Writef(LOG_LEVEL_ERR, "DeviceEnvironmentList Save DB : %+s", err.Error())
					} else {
						//						Logger.Writef(LOG_LEVEL_DEBUG, "DeviceEnvironmentList Save DB : %+v", e)
					}
				}
			}
		}

		// 制御条件
		if equipments.EquipmentControlCondition.EquipmentID != "" {
			var cc ControlConditions
			cc.TargetDevicesID = equipments.EquipmentControlCondition.EquipmentID
			cc.Name = equipments.EquipmentControlCondition.Name
			cc.ControlTime = int64(equipments.EquipmentControlCondition.ControlSeconds)
			cc.ReleaseControlTime = int64(equipments.EquipmentControlCondition.ControlReleaseSeconds)
			cc.ControlStartTemperature = equipments.EquipmentControlCondition.ControlStartTemperature
			cc.ControlStopTemperature = equipments.EquipmentControlCondition.ControlEndTemperature
			cc.ControlStartHumidity = equipments.EquipmentControlCondition.ControlStartHumidity
			cc.ControlStopHumidity = equipments.EquipmentControlCondition.ControlEndHumidity
			cc.ControlStartDiscomfortIndex = equipments.EquipmentControlCondition.ControlStartDiscomfortIndex
			cc.ControlStopDiscomfortIndex = equipments.EquipmentControlCondition.ControlEndDiscomfortIndex
			cc.DemandStartTemperature = equipments.EquipmentControlCondition.DemandControlStartTemperature
			cc.DemandStopTemperature = equipments.EquipmentControlCondition.DemandControlEndTemperature
			cc.DemandStartHumidity = equipments.EquipmentControlCondition.DemandControlStartHumidity
			cc.DemandStopHumidity = equipments.EquipmentControlCondition.DemandControlEndHumidity
			cc.DemandStartDiscomfortIndex = equipments.EquipmentControlCondition.DemandControlStartDiscomfortIndex
			cc.DemandStopDiscomfortIndex = equipments.EquipmentControlCondition.DemandControlEndDiscomfortIndex
			cc.ControlEnable = b2i8(equipments.EquipmentControlCondition.ControlTarget)
			cc.DemandEnable = b2i8(equipments.EquipmentControlCondition.DemandControlTarget)
			err := tx.Save(&cc).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "ControlConditions Save DB : %+s", err.Error())
				//} else {
				//	Logger.Writef(LOG_LEVEL_DEBUG, "ControlConditions Save DB : %+v", cc)
			}
		}
	}

	// Logger.Writef(LOG_LEVEL_DEBUG, "====================ChildUnit=======================\n")
	for _, v := range d.ChildDevices {
		if v.ID == "" {
			continue
		}

		// 子機情報
		var c ChildUnit
		c.ID = v.ID
		c.Name = v.Name
		c.Wireless = v.Wireless
		c.Enable = b2i8(v.Enabled)
		err := tx.Save(&c).Error
		if err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "ChildUnit Save DB : %+s", err.Error())
		} else {
			//			Logger.Writef(LOG_LEVEL_DEBUG, "ChildUnit Save DB : %+v", c)
		}

		// エネルギーセンサー
		for _, w := range v.EnergySensors {
			if w.ID == "" {
				continue
			}

			// エネルギーセンサー
			var e EnergySensor
			e.ID = w.ID
			e.Name = w.Name
			e.ChildDeviceID = w.ChildDeviceID
			e.DeviceName = w.DeviceName
			e.Voltage = float64(w.Voltage)
			e.PowerFactor = float64(w.PowerFactor)
			e.RatedPowerConsumptionCool = float64(w.CoolingRatedElectricPowerConsumption)
			e.RatedPowerConsumptionWarm = float64(w.HeatingRatedElectricPowerConsumption)
			e.ControlID = int16(w.ConnectionID)
			e.ControlChannel = int16(w.ConnectionChannel)
			e.Enable = b2i8(w.Enabled)
			err := tx.Save(&e).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "EnergySensor Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "EnergySensor Save DB : %+v", e)
			}

			// 監視条件
			for _, x := range w.SensorMonitoringConditions {
				if x.ID == "" {
					continue
				}
				var m MonitorConditions
				m.ID = x.ID
				m.Name = x.Name
				m.EnergySensorID = x.EnergySensorID
				m.EnvironmentSensorID = x.EnvironmentalSensorID
				m.InputContactID = x.InputContactID
				m.OutputContactID = x.OutputContactID
				m.MonitorCategory = x.Category
				m.Threshold = float64(x.Threshold)
				m.JudgementMethod = x.AnomalyType
				m.JudgementAbnormalTime = int64(x.AnomalyDurationSeconds)
				m.Message = x.Message
				m.Enable = b2i8(x.Enabled)
				err := tx.Save(&m).Error
				if err != nil {
					Logger.Writef(LOG_LEVEL_ERR, "MonitorConditions Save DB : %+s", err.Error())
				} else {
					Logger.Writef(LOG_LEVEL_DEBUG, "MonitorConditions Save DB : %+v", m)
				}
			}
		}

		// 環境センサー
		for _, w := range v.EnvironmentalSensors {
			if w.ID == "" {
				continue
			}

			// 環境センサー
			var e EnvironmentSensor
			e.ID = w.ID
			e.Name = w.Name
			e.ChildDeviceID = w.ChildDeviceID
			e.DeviceName = w.DeviceName
			e.Category = w.Category
			e.CorrectionValue = w.CorrectionAmount
			e.CorrectionRatio = w.CorrectionRatio
			e.ControlID = int16(w.ConnectionID)
			e.ControlChannel = int16(w.ConnectionChannel)
			e.Enable = b2i8(w.Enabled)
			err := tx.Save(&e).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "EnvironmentSensor Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "EnvironmentSensor Save DB : %+v", e)
			}

			// 監視条件
			for _, x := range w.SensorMonitoringConditions {
				if x.ID == "" {
					continue
				}
				var m MonitorConditions
				m.ID = x.ID
				m.Name = x.Name
				m.EnergySensorID = x.EnergySensorID
				m.EnvironmentSensorID = x.EnvironmentalSensorID
				m.InputContactID = x.InputContactID
				m.OutputContactID = x.OutputContactID
				m.MonitorCategory = x.Category
				m.Threshold = float64(x.Threshold)
				m.JudgementMethod = x.AnomalyType
				m.JudgementAbnormalTime = int64(x.AnomalyDurationSeconds)
				m.Message = x.Message
				m.Enable = b2i8(x.Enabled)
				err := tx.Save(&m).Error
				if err != nil {
					Logger.Writef(LOG_LEVEL_ERR, "MonitorConditions Save DB : %+s", err.Error())
				} else {
					Logger.Writef(LOG_LEVEL_DEBUG, "MonitorConditions Save DB : %+v", m)
				}
			}
		}

		// 入力接点
		for _, w := range v.InputContacts {
			if w.ID == "" {
				continue
			}

			// 入力接点
			var i InputContact
			i.ID = w.ID
			i.Name = w.Name
			i.ChildDeviceID = w.ChildDeviceID
			i.DeviceName = w.DeviceName
			i.Category = w.Category
			i.ControlID = int16(w.ConnectionID)
			i.ControlChannel = int16(w.ConnectionChannel)
			i.Enable = b2i8(w.Enabled)
			err := tx.Save(&i).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "InputContact Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "InputContact Save DB : %+v", i)
			}

			// 監視条件
			for _, x := range w.SensorMonitoringConditions {
				if x.ID == "" {
					continue
				}
				var m MonitorConditions
				m.ID = x.ID
				m.Name = x.Name
				m.EnergySensorID = x.EnergySensorID
				m.EnvironmentSensorID = x.EnvironmentalSensorID
				m.InputContactID = x.InputContactID
				m.OutputContactID = x.OutputContactID
				m.MonitorCategory = x.Category
				m.Threshold = float64(x.Threshold)
				m.JudgementMethod = x.AnomalyType
				m.JudgementAbnormalTime = int64(x.AnomalyDurationSeconds)
				m.Message = x.Message
				m.Enable = b2i8(x.Enabled)
				err := tx.Save(&m).Error
				if err != nil {
					Logger.Writef(LOG_LEVEL_ERR, "MonitorConditions Save DB : %+s", err.Error())
				} else {
					Logger.Writef(LOG_LEVEL_DEBUG, "MonitorConditions Save DB : %+v", m)
				}
			}
		}

		// 出力接点
		for _, w := range v.OutputContacts {
			if w.ID == "" {
				continue
			}

			// 出力接点
			var o OutputContact
			o.ID = w.ID
			o.Name = w.Name
			o.ChildDeviceID = w.ChildDeviceID
			o.DeviceName = w.DeviceName
			o.Category = w.Category
			o.ControlMethod = w.ControlMethod
			o.ControlID = int16(w.ConnectionID)
			o.ControlChannel = int16(w.ConnectionChannel)
			o.Enable = b2i8(w.Enabled)
			err := tx.Save(&o).Error
			if err != nil {
				Logger.Writef(LOG_LEVEL_ERR, "OutputContact Save DB : %+s", err.Error())
			} else {
				//				Logger.Writef(LOG_LEVEL_DEBUG, "OutputContact Save DB : %+v", o)
			}

			// 監視条件
			for _, x := range w.SensorMonitoringConditions {
				if x.ID == "" {
					continue
				}
				var m MonitorConditions
				m.ID = x.ID
				m.Name = x.Name
				m.EnergySensorID = x.EnergySensorID
				m.EnvironmentSensorID = x.EnvironmentalSensorID
				m.InputContactID = x.InputContactID
				m.OutputContactID = x.OutputContactID
				m.MonitorCategory = x.Category
				m.Threshold = float64(x.Threshold)
				m.JudgementMethod = x.AnomalyType
				m.JudgementAbnormalTime = int64(x.AnomalyDurationSeconds)
				m.Message = x.Message
				m.Enable = b2i8(x.Enabled)
				err := tx.Save(&m).Error
				if err != nil {
					Logger.Writef(LOG_LEVEL_ERR, "MonitorConditions Save DB : %+s", err.Error())
				} else {
					Logger.Writef(LOG_LEVEL_DEBUG, "MonitorConditions Save DB : %+v", m)
				}
			}
		}
	}

	// Logger.Writef(LOG_LEVEL_DEBUG, "====================DemandPulseUnit=======================\n")
	if d.DemandPulse.ID != "" {
		var demandPulseUnit DemandPulseUnit
		demandPulseUnit.ID = d.DemandPulse.ID
		demandPulseUnit.Name = d.DemandPulse.Name
		demandPulseUnit.DeviceName = d.DemandPulse.DeviceName
		demandPulseUnit.ElectricEnergyPerPulse = float64(d.DemandPulse.ElectricEnergyPerPulse)
		demandPulseUnit.ControlID = int16(d.DemandPulse.ConnectionID)
		demandPulseUnit.Threshold = float64(d.DemandPulse.BatteryLevelNotificationThreshold)
		demandPulseUnit.Enabled = b2i8(d.DemandPulse.NotificationEnabled)
		demandPulseUnit.JudgementAbnormalTime = int64(d.DemandPulse.AnomalyDurationSeconds)
		demandPulseUnit.Message = d.DemandPulse.Message
		err := tx.Save(&demandPulseUnit).Error
		if err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "DemandPulseUnit Save DB : %+s", err.Error())
		} else {
			//			Logger.Writef(LOG_LEVEL_DEBUG, "DemandPulseUnit Save DB : %+v", demandPulseUnit)
		}
	} else {
		Logger.Writef(LOG_LEVEL_DEBUG, "DemandPulseUnit not get from cloud")
	}
}

//========================================================================================================================
//	POST
//========================================================================================================================

// RequestAlertBattery 電池残量アラートの登録
func RequestAlertBattery(env Env, base string, t BatteryLevelAlert) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	params := measureapi.PostAlertBatteryJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		Id:         t.SensorID,
		MeasuredAt: measureapi.MeasuredAt(t.Time),
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertBattery(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestAlertConnection 通信アラート状況の登録
func RequestAlertConnection(env Env, base string, parent string, communicationAlerts []CommunicationAlert) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	childDeviceIds := []string{}
	demandPulseId := ""
	energySensorIds := []string{}
	environmentalSensorIds := []string{}
	inputContactIds := []string{}
	outputContactIds := []string{}

	for _, t := range communicationAlerts {
		switch t.Kind {
		case strChildUnit:
			childDeviceIds = append(childDeviceIds, t.SensorID)
		case strDemandPulseUnit:
			demandPulseId = t.SensorID
		case strEnergySensor:
			energySensorIds = append(energySensorIds, t.SensorID)
		case strEnvironmentalSensor:
			environmentalSensorIds = append(environmentalSensorIds, t.SensorID)
		case strInputContact:
			inputContactIds = append(inputContactIds, t.SensorID)
		case strOutputContact:
			outputContactIds = append(outputContactIds, t.SensorID)
		}
	}

	params := measureapi.PostAlertConnectionJSONRequestBody{
		BaseId:                 measureapi.BaseId(base),
		ChildDeviceIds:         childDeviceIds,
		DemandPulseId:          &demandPulseId,
		EnergySensorIds:        energySensorIds,
		EnvironmentalSensorIds: environmentalSensorIds,
		InputContactIds:        inputContactIds,
		MeasuredAt:             measureapi.MeasuredAt(time.Now().Unix()),
		OutputContactIds:       outputContactIds,
		ParentDeviceId:         parent,
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertConnection(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestAlertSensor センサー監視アラートの登録
func RequestAlertSensor(env Env, base string, t SensorMonitorAlert) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	occurredAt := measureapi.OccurredAt(t.OccurredAt)
	params := measureapi.PostAlertSensorJSONRequestBody{
		BaseId:                      measureapi.BaseId(base),
		Id:                          string(t.SensorID),
		Kind:                        measureapi.AlertSensorArgsKind(t.Kind),
		MeasuredAt:                  measureapi.MeasuredAt(t.Time),
		Message:                     string(strconv.FormatFloat(t.Value, 'f', -1, 64)),
		OccurredAt:                  &occurredAt,
		SensorMonitoringConditionId: string(t.MonitorConditionsID),
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertSensor(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestAlertUps UPSアラートの登録
func RequestAlertUps(env Env, base string, parent string, t UpsAlert) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	params := measureapi.PostAlertUpsJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		Id:         parent,
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Message:    t.Message,
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertUps(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestDemand デマンドデータの登録
func RequestDemand(env Env, base, parent string, t EnergyStatusDemand) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	params := measureapi.PostDemandJSONRequestBody{
		BaseId:               measureapi.BaseId(base),
		Id:                   parent,
		MeasuredAt:           measureapi.MeasuredAt(t.Time),
		CurrentElectricity:   measureapi.CurrentElectricity(t.CurrentElectricPower),
		DemandState:          measureapi.DemandState(t.AlarmStatus),
		PredictedElectricity: measureapi.PredictedElectricity(t.PredictedElectricPower),
		AdjustedElectricity:  measureapi.AdjustedElectricity(t.AdjustedElectricPower),
		RemainingSeconds:     measureapi.RemainingSeconds(t.TimeLeft),
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	Logger.Writef(LOG_LEVEL_DEBUG, "送信データ RequestDemand : %+v", params)
	// httpリクエスト送信（POST）
	res, err := c.PostDemand(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	return readPostResponse(res)
}

// RequestEnergySensor エネルギーセンサーの登録
func RequestEnergySensor(env Env, base string, t EnergyStatusElectricPower) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	energySensor := measureapi.EnergySensor{
		Id:                   t.EnergySensorID,
		ActiveElectricPower:  measureapi.ActiveElectricPower(t.EffectivePower),
		ActiveElectricEnergy: measureapi.ActiveElectricEnergy(t.EffectivePowerConsumption - t.PreEffectivePowerConsumption),
		ElectricCurrent1:     measureapi.ElectricCurrent1(t.Current1),
		ElectricCurrent2:     measureapi.ElectricCurrent2(t.Current2),
		ElectricCurrent3:     measureapi.ElectricCurrent3(t.Current3),
		Voltage1:             measureapi.Voltage1(t.Voltage1),
		Voltage2:             measureapi.Voltage2(t.Voltage2),
		Voltage3:             measureapi.Voltage3(t.Voltage3),
		Frequency:            measureapi.Frequency(t.Frequency),
		PowerFactor:          measureapi.PowerFactor(t.PowerFactor),
	}
	energySensors := measureapi.EnergySensors{energySensor}

	params := measureapi.PostEnergySensorJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Data:       energySensors,
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostEnergySensor(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestEnvironmentalSensor 環境センサーデータの登録
func RequestEnvironmentalSensor(env Env, base string, t EnvironmentSensorStatus) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	environmentalSensorArg := measureapi.EnvironmentalSensor{
		Id:              t.SensorID,
		Temperature:     measureapi.Temperature(t.Temperature),
		Humidity:        measureapi.Humidity(t.Humidity),
		DiscomfortIndex: measureapi.DiscomfortIndex(t.DiscomfortIndex),
	}
	environmentalSensorArgs := measureapi.EnvironmentalSensors{environmentalSensorArg}

	params := measureapi.PostEnvironmentalSensorJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Data:       environmentalSensorArgs}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostEnvironmentalSensor(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestEquipmentState 機器別ステートの登録
func RequestEquipmentState(env Env, base string, t DeviceStatus) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	equipmentState := measureapi.EquipmentState{
		Id:             t.DeviceID,
		ControlOrder:   measureapi.ControlOrder(i82b(t.Control)),
		ControlState:   measureapi.ControlState(t.Status),
		OperatingRate:  measureapi.OperatingRate(t.OccupancyRate),
		ElectricEnergy: measureapi.ElectricEnergy(t.ElectricEnergy),
		ElectricPower:  measureapi.ElectricPower(t.ElectricPower),
		Operating:      measureapi.Operating(t.Operating),
	}
	equipmentStateArgs := measureapi.EquipmentStates{equipmentState}

	params := measureapi.PostEquipmentStateJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Data:       equipmentStateArgs}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	//cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond10s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostEquipmentState(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_DEBUG, "Post deviceStatus :%+v", params)
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestInputContact 入力接点データの登録
func RequestInputContact(env Env, base string, t InputContactStatus) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	inputContact := measureapi.InputContact{
		Id:     t.SensorID,
		Status: i82b(t.Status),
	}
	inputContacts := measureapi.InputContacts{inputContact}

	params := measureapi.PostInputContactJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Data:       inputContacts}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostInputContact(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestOutputContact 出力接点データの登録
func RequestOutputContact(env Env, base string, t OutputContactStatus) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	outputContact := measureapi.OutputContact{
		Id:     t.SensorID,
		Status: i82b(t.Status),
	}
	outputContacts := measureapi.OutputContacts{outputContact}

	params := measureapi.PostOutputContactJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		Data:       outputContacts}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostOutputContact(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestPostAlertSystem 親機システムアラート
func RequestPostAlertSystem(env Env, base string, parent string, t SystemAlert) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	// 送信データ作成
	params := measureapi.PostAlertSystemJSONRequestBody{
		BaseId:     measureapi.BaseId(base),
		Id:         parent,
		MeasuredAt: measureapi.MeasuredAt(t.Time),
		ErrorCode:  t.ErrorCode,
		Message:    t.Message,
	}

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertSystem(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestPostDemandAlert デマンドアラートの登録
func RequestPostDemandAlert(env Env, base string, t EnergyAlertStatusDemand) (measureapi.PostResponse, error) {
	// クライアント作成
	c, _ := measureapi.NewClient(env.MeasureServerHost)

	var demandPulseUnit DemandPulseUnit
	result := database.GormDB.First(&demandPulseUnit)
	if result.Error != nil {
		return measureapi.PostResponse{}, result.Error
	}

	// 送信データ作成
	var status measureapi.DemandState
	switch t.AlarmStatus {
	case StrExcess:
		status = measureapi.Excess
	case Strlimit:
		status = measureapi.Limit
	case StrBeVigilant:
		status = measureapi.Warn
	case StrRecover:
		status = measureapi.Recover
	default:
		status = measureapi.Normal
	}
	message := fmt.Sprintf("現在電力: %f kW、予測電力: %f kW、調整電力: %f kW 目標電力: %f kW、限界電力: %f kW", t.CurrentElectricPower, t.PredictedElectricPower, t.AdjustedElectricPower, t.TargetElectricPower, t.ContactElectricPower)

	params := measureapi.PostAlertDemandJSONRequestBody{
		BaseId:      measureapi.BaseId(base),
		DemandState: status,
		Id:          demandPulseUnit.ID,
		MeasuredAt:  measureapi.MeasuredAt(t.Time),
		Message:     message,
	}
	Logger.Writef(LOG_LEVEL_DEBUG, "PostAlertDemandJSONRequestBody : %v", params)

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.PostAlertDemand(cloudCtx, params, MeasureAddXApiKey(env))
	if err != nil {
		return measureapi.PostResponse{}, err
	}

	// 応答確認
	return readPostResponse(res)
}

// RequestParentDevicesControllerCompleteParentDeviceRestart 親機の再起動完了を通知
func RequestParentDevicesControllerCompleteParentDeviceRestart(env Env, id string) (*syncapi.ParentDevicesControllerCompleteParentDeviceRestartResponse, error) {
	// クライアント作成
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	// 送信データ作成
	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.ParentDevicesControllerCompleteParentDeviceRestartWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	return res, err
}

// RequestEquipmentsControllerReleaseManualControlOrder 機器の緊急制御解除命令完了を通知
func RequestEquipmentsControllerReleaseManualControlOrder(env Env, id string) (*syncapi.EquipmentsControllerReleaseManualControlOrderResponse, error) {
	// クライアント作成
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	// 送信データ作成
	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond1s)
	defer cancel()

	// httpリクエスト送信（POST）
	res, err := c.EquipmentsControllerReleaseManualControlOrderWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	return res, err
}

//========================================================================================================================
//	GET
//========================================================================================================================

// RequestBasesControllerGetDemandControlOrder デマンド制御命令の取得
func RequestBasesControllerGetDemandControlOrder(env Env, id string) (syncapi.DemandControlOrderForLocal, error) {
	var p syncapi.DemandControlOrderForLocal

	// クライアント作成（レスポンスパーサー付き）
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond10s)
	defer cancel()

	// httpリクエスト送信（GET）- レスポンスパーサー関数が自動的に呼ばれる
	res, err := c.BasesControllerGetDemandControlOrderWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder request error: %s", err.Error())
		return p, err
	}

	// レスポンスステータスコードのチェック
	switch {
	case res.JSON200 != nil:
		// 200 OK: 正常なレスポンス
		Logger.Writef(LOG_LEVEL_DEBUG, "RequestBasesControllerGetDemandControlOrder success: %+v", *res.JSON200)
		return *res.JSON200, nil

	case res.JSON403 != nil:
		// 403 Forbidden: 認証エラー
		statusCode := 403
		if res.JSON403.StatusCode != nil {
			statusCode = *res.JSON403.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder HTTP 403 Forbidden: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case res.JSON404 != nil:
		// 404 Not Found: リソースが見つからない
		statusCode := 404
		if res.JSON404.StatusCode != nil {
			statusCode = *res.JSON404.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder HTTP 404 Not Found: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 404 Not Found: demand control order not found")

	case res.JSON500 != nil:
		// 500 Internal Server Error: サーバーエラー
		statusCode := 500
		if res.JSON500.StatusCode != nil {
			statusCode = *res.JSON500.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder HTTP 500 Internal Server Error: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case res.JSON503 != nil:
		// 503 Service Unavailable: サービス利用不可
		message := "Service Unavailable"
		if res.JSON503.Message != nil {
			message = *res.JSON503.Message
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder HTTP 503 Service Unavailable: %s", message)
		return p, fmt.Errorf("HTTP 503 Service Unavailable: %s", message)

	default:
		// その他のステータスコード（200以外でパースされなかった場合）
		statusCode := 0
		if res.HTTPResponse != nil {
			statusCode = res.HTTPResponse.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetDemandControlOrder unexpected HTTP status: %d, body: %s", statusCode, string(res.Body))
		return p, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}

// RequestBasesControllerGetManualControlOrders 機器の手動制御命令の取得
func RequestBasesControllerGetManualControlOrders(env Env, id string) ([]syncapi.ManualControlOrderForLocal, error) {
	var p []syncapi.ManualControlOrderForLocal

	// クライアント作成（レスポンスパーサー付き）
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond10s)
	defer cancel()

	// httpリクエスト送信（GET）- レスポンスパーサー関数が自動的に呼ばれる
	res, err := c.BasesControllerGetManualControlOrdersWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders request error: %s", err.Error())
		return p, err
	}

	// レスポンスステータスコードのチェック
	switch {
	case res.JSON200 != nil:
		// 200 OK: 正常なレスポンス
		Logger.Writef(LOG_LEVEL_DEBUG, "RequestBasesControllerGetManualControlOrders success: count=%d", len(*res.JSON200))
		return *res.JSON200, nil

	case res.JSON403 != nil:
		// 403 Forbidden: 認証エラー
		statusCode := 403
		if res.JSON403.StatusCode != nil {
			statusCode = *res.JSON403.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders HTTP 403 Forbidden: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case res.JSON404 != nil:
		// 404 Not Found: リソースが見つからない
		statusCode := 404
		if res.JSON404.StatusCode != nil {
			statusCode = *res.JSON404.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders HTTP 404 Not Found: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 404 Not Found: manual control orders not found")

	case res.JSON500 != nil:
		// 500 Internal Server Error: サーバーエラー
		statusCode := 500
		if res.JSON500.StatusCode != nil {
			statusCode = *res.JSON500.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders HTTP 500 Internal Server Error: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case res.JSON503 != nil:
		// 503 Service Unavailable: サービス利用不可
		message := "Service Unavailable"
		if res.JSON503.Message != nil {
			message = *res.JSON503.Message
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders HTTP 503 Service Unavailable: %s", message)
		return p, fmt.Errorf("HTTP 503 Service Unavailable: %s", message)

	default:
		// その他のステータスコード（200以外でパースされなかった場合）
		statusCode := 0
		if res.HTTPResponse != nil {
			statusCode = res.HTTPResponse.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualControlOrders unexpected HTTP status: %d, body: %s", statusCode, string(res.Body))
		return p, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}

// RequestBasesControllerGetManualDefrostOrders 出力接点の手動デフロスト命令の取得
func RequestBasesControllerGetManualDefrostOrders(env Env, id string) ([]syncapi.ManualDefrostOrderForLocal, error) {
	var p []syncapi.ManualDefrostOrderForLocal

	// クライアント作成（レスポンスパーサー付き）
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond10s)
	defer cancel()

	// httpリクエスト送信（GET）- レスポンスパーサー関数が自動的に呼ばれる
	res, err := c.BasesControllerGetManualDefrostOrdersWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders request error: %s", err.Error())
		return p, err
	}

	// レスポンスステータスコードのチェック
	switch {
	case res.JSON200 != nil:
		// 200 OK: 正常なレスポンス
		Logger.Writef(LOG_LEVEL_DEBUG, "RequestBasesControllerGetManualDefrostOrders success: count=%d", len(*res.JSON200))
		return *res.JSON200, nil

	case res.JSON403 != nil:
		// 403 Forbidden: 認証エラー
		statusCode := 403
		if res.JSON403.StatusCode != nil {
			statusCode = *res.JSON403.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders HTTP 403 Forbidden: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case res.JSON404 != nil:
		// 404 Not Found: リソースが見つからない
		statusCode := 404
		if res.JSON404.StatusCode != nil {
			statusCode = *res.JSON404.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders HTTP 404 Not Found: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 404 Not Found: manual defrost orders not found")

	case res.JSON500 != nil:
		// 500 Internal Server Error: サーバーエラー
		statusCode := 500
		if res.JSON500.StatusCode != nil {
			statusCode = *res.JSON500.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders HTTP 500 Internal Server Error: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case res.JSON503 != nil:
		// 503 Service Unavailable: サービス利用不可
		message := "Service Unavailable"
		if res.JSON503.Message != nil {
			message = *res.JSON503.Message
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders HTTP 503 Service Unavailable: %s", message)
		return p, fmt.Errorf("HTTP 503 Service Unavailable: %s", message)

	default:
		// その他のステータスコード（200以外でパースされなかった場合）
		statusCode := 0
		if res.HTTPResponse != nil {
			statusCode = res.HTTPResponse.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestBasesControllerGetManualDefrostOrders unexpected HTTP status: %d, body: %s", statusCode, string(res.Body))
		return p, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}

// RequestParentDevicesControllerGetBase 親機に紐づくデータを取得
func RequestParentDevicesControllerGetBase(env Env, id string) (*AutoGenerated, error) {
	// クライアント作成（レスポンスパーサー付き）
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	// 親機データはデータ量が多いのでタイムアウトを長くしておく
	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond30s)
	defer cancel()

	// httpリクエスト送信（GET）- レスポンスパーサー関数が自動的に呼ばれる
	res, err := c.ParentDevicesControllerGetParentDeviceWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase request error: %s", err.Error())
		return nil, err
	}

	// レスポンスステータスコードのチェック
	switch {
	case res.JSON200 != nil:
		// 200 OK: 正常なレスポンス
		Logger.Writef(LOG_LEVEL_DEBUG, "RequestParentDevicesControllerGetBase success, data size: %d", len(res.Body))

		// ParentDeviceForLocal -> AutoGenerated への変換（JSON経由）
		// レスポンスボディをそのまま使用（既にパース済みだが、AutoGenerated形式に変換するため）
		var p AutoGenerated
		if err := json.Unmarshal(res.Body, &p); err != nil {
			Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase JSON unmarshal error: %s", err.Error())
			return nil, err
		}
		return &p, nil

	case res.JSON403 != nil:
		// 403 Forbidden: 認証エラー
		statusCode := 403
		if res.JSON403.StatusCode != nil {
			statusCode = *res.JSON403.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase HTTP 403 Forbidden: statusCode=%d", statusCode)
		return nil, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case res.JSON404 != nil:
		// 404 Not Found: リソースが見つからない
		statusCode := 404
		if res.JSON404.StatusCode != nil {
			statusCode = *res.JSON404.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase HTTP 404 Not Found: statusCode=%d", statusCode)
		return nil, fmt.Errorf("HTTP 404 Not Found: parent device not found")

	case res.JSON500 != nil:
		// 500 Internal Server Error: サーバーエラー
		statusCode := 500
		if res.JSON500.StatusCode != nil {
			statusCode = *res.JSON500.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase HTTP 500 Internal Server Error: statusCode=%d", statusCode)
		return nil, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case res.JSON503 != nil:
		// 503 Service Unavailable: サービス利用不可
		message := "Service Unavailable"
		if res.JSON503.Message != nil {
			message = *res.JSON503.Message
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase HTTP 503 Service Unavailable: %s", message)
		return nil, fmt.Errorf("HTTP 503 Service Unavailable: %s", message)

	default:
		// その他のステータスコード（200以外でパースされなかった場合）
		statusCode := 0
		if res.HTTPResponse != nil {
			statusCode = res.HTTPResponse.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetBase unexpected HTTP status: %d, body: %s", statusCode, string(res.Body))
		return nil, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}

// RequestParentDevicesControllerGetParentDeviceRestartOrder 親機の再起動命令を取得
func RequestParentDevicesControllerGetParentDeviceRestartOrder(env Env, id string) (syncapi.ParentDeviceRestartOrderForLocal, error) {
	var p syncapi.ParentDeviceRestartOrderForLocal

	// クライアント作成（レスポンスパーサー付き）
	c, _ := syncapi.NewClientWithResponses(env.SyncServerHost)

	cloudCtx, cancel := context.WithTimeout(context.Background(), cloudTimeoutSecond10s)
	defer cancel()

	// httpリクエスト送信（GET）- レスポンスパーサー関数が自動的に呼ばれる
	res, err := c.ParentDevicesControllerGetParentDeviceRestartOrderWithResponse(cloudCtx, id, SyncAddXApiKey(env))
	if err != nil {
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder request error: %s", err.Error())
		return p, err
	}

	// レスポンスステータスコードのチェック
	switch {
	case res.JSON200 != nil:
		// 200 OK: 正常なレスポンス
		Logger.Writef(LOG_LEVEL_DEBUG, "RequestParentDevicesControllerGetParentDeviceRestartOrder success: %+v", *res.JSON200)
		return *res.JSON200, nil

	case res.JSON403 != nil:
		// 403 Forbidden: 認証エラー
		statusCode := 403
		if res.JSON403.StatusCode != nil {
			statusCode = *res.JSON403.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder HTTP 403 Forbidden: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 403 Forbidden: access denied")

	case res.JSON404 != nil:
		// 404 Not Found: リソースが見つからない
		statusCode := 404
		if res.JSON404.StatusCode != nil {
			statusCode = *res.JSON404.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder HTTP 404 Not Found: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 404 Not Found: parent device restart order not found")

	case res.JSON500 != nil:
		// 500 Internal Server Error: サーバーエラー
		statusCode := 500
		if res.JSON500.StatusCode != nil {
			statusCode = *res.JSON500.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder HTTP 500 Internal Server Error: statusCode=%d", statusCode)
		return p, fmt.Errorf("HTTP 500 Internal Server Error: server error")

	case res.JSON503 != nil:
		// 503 Service Unavailable: サービス利用不可
		message := "Service Unavailable"
		if res.JSON503.Message != nil {
			message = *res.JSON503.Message
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder HTTP 503 Service Unavailable: %s", message)
		return p, fmt.Errorf("HTTP 503 Service Unavailable: %s", message)

	default:
		// その他のステータスコード（200以外でパースされなかった場合）
		statusCode := 0
		if res.HTTPResponse != nil {
			statusCode = res.HTTPResponse.StatusCode
		}
		Logger.Writef(LOG_LEVEL_ERR, "RequestParentDevicesControllerGetParentDeviceRestartOrder unexpected HTTP status: %d, body: %s", statusCode, string(res.Body))
		return p, fmt.Errorf("HTTP request failed with unexpected status %d", statusCode)
	}
}
