@startuml 制御状態のステート図
title 制御状態のステート図

[*] -> 自動制御中 :システム 起動
'自動制御中--> 無制御 : 自動制御可否\n不一致
自動制御中 : do / 圧縮機・室外機の停止・解除
自動制御中 : do / デフロストの停止・解除
自動制御中 -> 遠隔制御中 : 遠隔制御命令\nON
自動制御中 ---> デマンド制御中 : 遠隔制御命令\nOFF\n&\nデマンド制御命令\nON\n&\nデマンド逼迫(調整電力≧ 0)
'無制御--> 遠隔制御中 : 遠隔制御命令\nON
'無制御 --> デマンド制御中 : デマンド制御命令\nON
'無制御 --> 自動制御中 : 自動制御可否\n一致

デマンド制御中 ---> 自動制御中 : デマンド制御命令\nor\nOFF調整電力 ≦ 「復帰電力」
デマンド制御中 : do / 圧縮機・室外機の停止・解除
デマンド制御中 : do / デフロストの停止・解除
'\n&\n遠隔制御命令\nOFF
'デマンド制御中 --> 自動制御中 : デマンド制御命令\nOFF\nOR\nクラウド間通信切れ
デマンド制御中 -> 遠隔制御中 : 遠隔制御命令\nON

遠隔制御中 -> 自動制御中 : 遠隔制御命令\nOFF
遠隔制御中 : do / 圧縮機・室外機の停止
遠隔制御中 : do / デフロストの停止・解除
'\n &\nデマンド制御命令\nOFF\n自動制御可否\n&\n不一致
'遠隔制御中 --> 自動制御中 : 遠隔制御命令\nOFF\n&\nデマンド制御命令\nOFF\n&\n自動制御可否\n一致
'遠隔制御中 ---> デマンド制御中 : 遠隔制御命令\nOFF\n&\nデマンド制御命令\nON\n&\nデマンド逼迫(調整電力≧ 0)





@enduml